### ISSUE TITLE
所有页面pop的使用场景报错

### ISSUE THREAD

**Issue by xxzj990** [MMMzq/bot_toast#1]
如果项目使用到：
Navigator.of(context).pushAndRemoveUntil

去打开页面，插件会失效。如果再次初始化会报错。【不允许初始化多次!】

**Comment by MMMzq** [comment]
你是使用Navigator.of(context).pushAndRemoveUntil把第一Route也删除掉才会出现这种情况吗？
其实这个并不算bug,只是代码检测到重复初始化了,按照设计现在是不可以初始化多次的,我这边可以放宽一下检查程度

**Comment by MMMzq** [comment]
@xxzj990  已更新到1.0.2版本,你升级下就应该好了,方便的话能说一下重现流程吗？

**Comment by xxzj990** [comment]
@MMMzq 你好，场景是这样的：
1、打开应用后到首页
2、检查用户登录，未登录时，pop所有页面，并push登录页面(用的系统函数：Navigator.of(context).pushAndRemoveUntil)
3、登录

还有一种场景是退出登录也和上面类似，都会有pop之前所有页面的操作

**Comment by xxzj990** [comment]
@MMMzq 我试试1.0.2

**Comment by xxzj990** [comment]
![微信截图_20190722092931](https://user-images.githubusercontent.com/5134154/61600603-0ad5c680-ac64-11e9-99a4-69fe24cfc3cc.png)

1.0.2初始化不报错，但是使用(BotToast.showText)的时候会报错，如上图。

**Comment by xxzj990** [comment]
Navigator.of(context).pushAndRemoveUntil这个函数会把所有Route干掉，重新打开新的

**Comment by MMMzq** [comment]
👌,我feel到你的意思了,解决了我会通知你的

**Comment by MMMzq** [comment]
问题找到了,主要问题是Navigator的Route为空时会导致Route生成的OverlayEntry会直接插入到Overlay持有OverlayEntry最后面.

这个问题需要点时间来解决,可能需要重构整个库的代码,所以可能没那么快修复这个bug

**Comment by MMMzq** [comment]
@xxzj990

**Comment by MMMzq** [comment]
@xxzj990 
以更新到1.0.3版本,你再试试这个版本看有没有问题

**Comment by xxzj990** [comment]
@MMMzq 好的

**Comment by xxzj990** [comment]
@MMMzq 问题已解决！
