### ISSUE TITLE
支持Navigator 2.0吗

### ISSUE THREAD

**Issue by a582468113** [MMMzq/bot_toast#100]
如何支持

**Comment by MMMzq** [comment]
应该支持的,`BotToast`本身仅仅依赖`Navigator.observers`功能,核心实现并不是靠`Navigator`实现的

**Comment by s-sy** [comment]
使用了auto_router 这种我要怎么整合进去，试了文档上的好像不行，
 MaterialApp｛
      build : ExtendedNavigator(
          router: route.Router(),
          ),
｝

**Comment by MMMzq** [comment]
请注意看文档谢谢:   https://github.com/MMMzq/bot_toast#3-initialization-bottoast
