### ISSUE TITLE
bot_toast导致flutter无法热加载

### ISSUE THREAD

**Issue by jinyuanqing** [MMMzq/bot_toast#104]
bot_toast导致flutter无法热加载
 
 - Flutter Version: [e.g. v1.5.0]1.24.0
 - OS: [e.g. iOS/Android]web
 - BotToast Version : [e.g. 0.3.0]3.0.5

**Comment by MMMzq** [comment]
请说一下具体情况或者步骤,你这样我帮不了你

**Comment by jinyuanqing** [comment]
已经找到原因了.好像是这个库和哪里有些冲突.我屏蔽bot_toast初始化后,又好用了.等我再次发生无法热重载的情况,我再来反馈下.目前又好用了.
