### ISSUE TITLE
BotToast.showCustomLoading() 遇到问题

### ISSUE THREAD

**Issue by xqdad** [MMMzq/bot_toast#107]
版本：bot_toast: ^4.0.0+1

BotToast.showCustomLoading()  的参数 toastBuilder 我放的是一个 StatefulWidget 的菊花，做了个延迟 10秒后自动出现一个叉，点击叉调用  toastBuilder 的 CancelFunc 函数，然后就异常（如下），我猜是因为我再次调用了一下 BotToast.showCustomLoading() 返回的函数，

使用情景是：
var cb = BotToast.showCustomLoading() ;
//发起请求
//请求中时由于请求太慢，先调用了 toastBuilder 的 CancelFunc 函数（提前关闭了菊花）
//请求结束
cb();（请求结束后还调用了 cb 函数，然后就下面异常了，大佬麻烦能把返回的关闭回调改成可空吗）

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 488 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:488:7)
#3      BotToast.showAnimationWidget.<anonymous closure> (package:bot_toast/src/toast.dart:672:37)
#4      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:770:24)
#5      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:769:36)

**Comment by MMMzq** [comment]
这是个bug,正常情况CancelFunc是可以重复调用的

**Comment by xqdad** [comment]
> 这是个bug,正常情况CancelFunc是可以重复调用的

感谢！

**Comment by MMMzq** [comment]
@xqdad 
新版本迟点发布

**Comment by xqdad** [comment]
> @xqdad
> 新版本迟点发布

好的，谢谢大佬

**Comment by MMMzq** [comment]
`v4.0.1`已发布
