### ISSUE TITLE
Flexible Builder for `MaterialApp` which allows to pass on a child

### ISSUE THREAD

**Issue by BirjuVachhani** [MMMzq/bot_toast#108]
**Describe the bug**
Current implementation of the builder `BotToastInit` can't be used to wrap other widgets around.

**To Reproduce**
Let's say. I wanna fix the `textScaleFactor` across the app. Best way to do this is to copy `MediaQuery` in `MaterialApp`
s builder with value `textScaleFactor: 1.0`. I cannot do that because `BotToastInit` returns a `TransitionBuilder` instead of `Widget`.

Example: This code doesn't compile.
```dart
MaterialApp(
  debugShowCheckedModeBanner: false,
  theme: theme,
  navigatorKey: navigatorKey,
  builder: (ctx, child) => MediaQuery(
    data: MediaQuery.of(ctx).copyWith(textScaleFactor: 1.0),
    child: BotToastInit(),
  ),
);
```

**Expected behavior**
It should allow to wrap other widget in the builder of `MaterialApp`.

Example: Expected Behavior
```dart
MaterialApp(
  debugShowCheckedModeBanner: false,
  theme: theme,
  navigatorKey: navigatorKey,
  builder: (ctx, child) => MediaQuery(
    data: MediaQuery.of(ctx).copyWith(textScaleFactor: 1.0),
    child: BotToastInitBuilder(child: child),
  ),
);
```

**Screenshots**
- None

**Version (please complete the following information):**
 - Flutter Version: 2.0.1
 - OS: iOS & Android
 - BotToast Version : 4.0.1

**Additional context**
- `BotToastInit` returns a `TransitionBuilder` which is ideal when there's no other configuration inside `MaterialApp`'s builder. But to allow other configurations to co-exist, something like `BotToastInitBuilder` should be there which returns a `Widget` instead of `TransitionBuilder` which is similar to `BotToastManager` (which is not exposed outside the library so can't use it.)

**Comment by MMMzq** [comment]
This can help you:
```dart
    final botToastBuilder =  BotToastInit();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: theme,
      navigatorKey: navigatorKey,
      builder: (ctx, child) => MediaQuery(
        data: MediaQuery.of(ctx).copyWith(textScaleFactor: 1.0),
        child: botToastBuilder(ctx,child),
      ),
    );
```
[Docs](https://github.com/MMMzq/bot_toast#3-initialization-bottoast)

**Comment by BirjuVachhani** [comment]
@MMMzq Yeah, I am using it that way right now but it doesn't seem clean to me.

**Comment by MMMzq** [comment]
https://github.com/MMMzq/bot_toast/blob/2d3bae978b7f79316dd5202082150a6ec8d3eb87/lib/src/bot_toast_init.dart#L49

> @MMMzq Yeah, I am using it that way right now but it doesn't seem clean to me.

The main reason for using `BotToastInit` instead of `BotToastInitBuilder` is to ensure the initialization of `BotToastWidgetsBindingObserver._singleton`.

**Comment by BirjuVachhani** [comment]
@MMMzq Yeah, it does that too. It is just that we don't have to use it this way:

```dart
final botToastBuilder =  BotToastInit();
return MaterialApp(
  debugShowCheckedModeBanner: false,
  theme: theme,
  navigatorKey: navigatorKey,
  builder: (ctx, child) => MediaQuery(
    data: MediaQuery.of(ctx).copyWith(textScaleFactor: 1.0),
    child: botToastBuilder(ctx, child),
  ),
);
```

or this way:

```dart
return MaterialApp(
  debugShowCheckedModeBanner: false,
  theme: theme,
  navigatorKey: navigatorKey,
  builder: (ctx, child) => MediaQuery(
    data: MediaQuery.of(ctx).copyWith(textScaleFactor: 1.0),
    child: BotToastInit().call(ctx, child),
  ),
);
```

I find my solution much cleaner to use. However it's your call now.

**Comment by BirjuVachhani** [comment]
Sorry...mistakenly closed it.

**Comment by MMMzq** [comment]
@BirjuVachhani 
It cannot be initialized with the following method, because the following method will cause the registration order of `addObserver` to be wrong!
See:

https://github.com/MMMzq/bot_toast/blob/2d3bae978b7f79316dd5202082150a6ec8d3eb87/lib/src/bot_toast_init.dart#L14-L16


https://github.com/MMMzq/bot_toast/blob/2d3bae978b7f79316dd5202082150a6ec8d3eb87/lib/src/toast.dart#L806-L820


https://github.com/flutter/flutter/blob/7dd752ace6932fe9a0fe35f4e34d4bfa520ec60a/packages/flutter/lib/src/widgets/app.dart#L1123-L1139

**Comment by BirjuVachhani** [comment]
I didn't get your point. I tested it with `BotToastInitBuilder` and it was working fine. It is the almost code as `BotToastInit`'s code.

**Comment by MMMzq** [comment]
Using the above method will cause the unexpected behavior of `backButtonBehavior`.

```dart
return MaterialApp(
  debugShowCheckedModeBanner: false,
  theme: theme,
  navigatorKey: navigatorKey,
  builder: (ctx, child) => MediaQuery(
    data: MediaQuery.of(ctx).copyWith(textScaleFactor: 1.0),
    child: BotToastInit().call(ctx, child),
  ),
);
```


![issues109](https://user-images.githubusercontent.com/28224568/111577505-5ea80280-87ed-11eb-860e-1da8fdf1f323.gif)

**Comment by BirjuVachhani** [comment]
Gotcha!
