### ISSUE TITLE
[Feature Request] Border Color?

### ISSUE THREAD

**Issue by awarmfastbear** [MMMzq/bot_toast#111]
Could you please consider adding a border color that could accept a Theme color?

When a white toast notification is displayed over a white background it is difficult to see the outline of the notification. A border would help solve this as well as making the appearance nicer.

Increasing the borderRadius size is the only current mitigation

**Comment by MMMzq** [comment]
You can try to use the following API.
```dart
BotToast.showCustomNotification(...)
BotToast.showCustomText(...)
BotToast.showCustomLoading(...)
BotToast.showAnimationWidget(...)
```

**Comment by awarmfastbear** [comment]
not relevant

**Comment by MMMzq** [comment]
1. If the style does not meet the requirements, you can customize Toast by Custom Api.
2. There are too many method parameters now, and no more parameters will be added unless necessary

See: 
https://github.com/MMMzq/bot_toast/blob/master/lib/src/toast_widget/text.dart
https://github.com/MMMzq/bot_toast/blob/2d3bae978b7f79316dd5202082150a6ec8d3eb87/lib/src/toast.dart#L325-L331
