### ISSUE TITLE
无法弹出 toast

### ISSUE THREAD

**Issue by FlyingNoob** [MMMzq/bot_toast#115]
**Describe the bug**
当使用了 Navigator.pushReplacement  push到新的页面之后，toast 不展示
**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.22.5]
 - BotToast Version : [e.g. 3.0.5]

**Additional context**

**Comment by MMMzq** [comment]
你好，能把大概的上下文描述一下吗?或者写一个demo也可以

**Comment by FlyingNoob** [comment]
@MMMzq 找到具体问题了，在当前页面 app 配置初始化 bottoast。 按钮在appbar 上，然后点击事件直接push到另外的页面，被push的页面 无法弹出。

**Comment by MMMzq** [comment]
你还我尝试了一下复现你说的情况,但是没能复现出来,能提供一个最小的demo吗?
