### ISSUE TITLE
NoSuchMethodError: The getter 'overlay' was called on null. Receiver: null Tried calling: overlay.

### ISSUE THREAD

**Issue by Mhsanjib** [MMMzq/bot_toast#120]
**Describe the bug**
I am getting the issue **"NoSuchMethodError: The getter 'overlay' was called on null. Receiver: null Tried calling: overlay. Error thrown Instance of 'ErrorDescription'. BotToastManager.<fn>"** from the crashlytics dashboard of my live flutter app.

Here are more logs for this issue:
```
BotToastManager.<fn> (bot_toast_manager.dart:122)
safeRun.<fn> (bot_toast_manager.dart:11)
SchedulerBinding._invokeFrameCallback (binding.dart:1117)
SchedulerBinding.handleDrawFrame (binding.dart:1063)
SchedulerBinding._handleDrawFrame (binding.dart:971)
```

Please have a look into this. Thank you.

**Comment by MMMzq** [comment]
**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

Can you provide a demo for the problem?
