### ISSUE TITLE
Bot toasts appearing behind bottom sheet modal

### ISSUE THREAD

**Issue by Nealsoni00** [MMMzq/bot_toast#121]
**Describe the bug**
When a bottom sheet modal is in view of the screen, new Bot Toasts don't appear on the top layer of the screen. They appear behind the bottom sheet modal (blurred out and hidden). 

**To Reproduce**
1. Open a bottom sheet modal
2. Trigger a bot toast notification

**Expected behavior**
Ideally the bot_toasts would appear on the top layer

**Version (please complete the following information):**
 - Flutter Version: 2.2.1
 - OS: iOS/Android
 - BotToast Version : ^4.0.1

**Comment by Nealsoni00** [comment]
![image](https://user-images.githubusercontent.com/7013191/128109611-76a3f0a4-4801-486c-b35f-6901765b4bb4.png)

**Comment by MMMzq** [comment]
I use the `showBottomSheet` method to work fine.
If other third-party libraries are used, it may be caused by the priority of the third library.
