### ISSUE TITLE
我这边碰到在使用Getx 路由跳转的页面后，弹框无法出现？

### ISSUE THREAD

**Issue by YI--** [MMMzq/bot_toast#123]
**Describe the bug**

Getx 路由管理 与BotToast 冲突？

**To Reproduce**
1、引入BotToast与GetX
2、使用Getx的路由跳转页面，不用区分是否命名路由
3、在跳转到的页面添加个button用来toast弹窗，点击直接无效果，也无日志。

可以弹Toast（系统路由）
`Navigator.push(
              context,
              MaterialPageRoute(builder: (context) {
                return xxx();
              }),
            );
`

不可以弹Toast（GetX路由）
`
Get.to(() => xxx());
Get.toNamed('/xxxx');
`

**Expected behavior**

可以不受影响的使用

**Version (please complete the following information):**
bot_toast: ^4.0.1

get: ^4.3.8

Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (3 weeks ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2

**Additional context**

**Comment by MMMzq** [comment]
```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    /// 初始化Toast
    final botToastBuilder = BotToastInit();

    return GetMaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (context, child) {
        /// 添加Toast
        child = botToastBuilder(context, child);
        return child;
      },
      navigatorObservers: [
        /// 添加Toast导航
        BotToastNavigatorObserver()
      ],
      home: const HomeRoute(),
    );
  }
}```
这种方式正常工作.
出现问题是因为demo重复嵌套了App这个Widget
