### ISSUE TITLE
Made a new flutter project, copied code, got over 30 errors 

### ISSUE THREAD

**Issue by AppDevelopmentCorps** [MMMzq/bot_toast#126]
Using library   bot_toast: ^4.0.0 #null safety 
in a new Flutter project, getting all these errors, almost everything is red 

Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
lib/custom/custom_animation.dart:137:36: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomAnimationWidget({Key key, this.controller, this.child})
                                   ^^^
lib/custom/custom_animation.dart:137:46: Error: The parameter 'controller' can't have a value of 'null' because of its type 'AnimationController', but the implicit default value is 'null'.
 - 'AnimationController' is from 'package:flutter/src/animation/animation_controller.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation_controller.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomAnimationWidget({Key key, this.controller, this.child})
                                             ^^^^^^^^^^
lib/custom/custom_animation.dart:137:63: Error: The parameter 'child' can't have a value of 'null' because of its type 'Widget', but the implicit default value is 'null'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomAnimationWidget({Key key, this.controller, this.child})
                                                              ^^^^^
lib/custom/custom_animation.dart:187:12: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
      {Key key, this.controller, this.child, this.reverse = false})
           ^^^
lib/custom/custom_animation.dart:187:22: Error: The parameter 'controller' can't have a value of 'null' because of its type 'AnimationController', but the implicit default value is 'null'.
 - 'AnimationController' is from 'package:flutter/src/animation/animation_controller.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation_controller.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
      {Key key, this.controller, this.child, this.reverse = false})
                     ^^^^^^^^^^
lib/custom/custom_animation.dart:187:39: Error: The parameter 'child' can't have a value of 'null' because of its type 'Widget', but the implicit default value is 'null'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
      {Key key, this.controller, this.child, this.reverse = false})
                                      ^^^^^
lib/custom/custom_animation.dart:231:38: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomAttachedAnimation({Key key, this.controller, this.child})
                                     ^^^
lib/custom/custom_animation.dart:231:48: Error: The parameter 'controller' can't have a value of 'null' because of its type 'AnimationController', but the implicit default value is 'null'.
 - 'AnimationController' is from 'package:flutter/src/animation/animation_controller.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation_controller.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomAttachedAnimation({Key key, this.controller, this.child})
                                               ^^^^^^^^^^
lib/custom/custom_animation.dart:231:65: Error: The parameter 'child' can't have a value of 'null' because of its type 'Widget', but the implicit default value is 'null'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomAttachedAnimation({Key key, this.controller, this.child})
                                                                ^^^^^
lib/custom/custom_widget.dart:6:19: Error: The parameter 'cancel' can't have a value of 'null' because of its type 'void Function()', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
    {VoidCallback cancel,
                  ^^^^^^
lib/custom/custom_widget.dart:7:18: Error: The parameter 'confirm' can't have a value of 'null' because of its type 'void Function()', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
    VoidCallback confirm,
                 ^^^^^^^
lib/custom/custom_widget.dart:8:20: Error: The parameter 'backgroundReturn' can't have a value of 'null' because of its type 'void Function()', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
      VoidCallback backgroundReturn}) {
                   ^^^^^^^^^^^^^^^^
lib/custom/custom_widget.dart:152:36: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomOffsetAnimation({Key key, this.controller, this.child})
                                   ^^^
lib/custom/custom_widget.dart:152:46: Error: The parameter 'controller' can't have a value of 'null' because of its type 'AnimationController', but the implicit default value is 'null'.
 - 'AnimationController' is from 'package:flutter/src/animation/animation_controller.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation_controller.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomOffsetAnimation({Key key, this.controller, this.child})
                                             ^^^^^^^^^^
lib/custom/custom_widget.dart:152:63: Error: The parameter 'child' can't have a value of 'null' because of its type 'Widget', but the implicit default value is 'null'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const CustomOffsetAnimation({Key key, this.controller, this.child})
                                                              ^^^^^
lib/loading/custom_loading.dart:8:32: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const _CustomLoadWidget({Key key, this.cancelFunc}) : super(key: key);
                               ^^^
lib/loading/custom_loading.dart:8:42: Error: The parameter 'cancelFunc' can't have a value of 'null' because of its type 'void Function()', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const _CustomLoadWidget({Key key, this.cancelFunc}) : super(key: key);
                                         ^^^^^^^^^^
lib/notification/custom_notification.dart:8:28: Error: The parameter 'key' can't have a value of 'null' because of its type 'Key', but the implicit default value is 'null'.
 - 'Key' is from 'package:flutter/src/foundation/key.dart' ('/C:/src/flutter/packages/flutter/lib/src/foundation/key.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const _CustomWidget({Key key, this.cancelFunc}) : super(key: key);
                           ^^^
lib/notification/custom_notification.dart:8:38: Error: The parameter 'cancelFunc' can't have a value of 'null' because of its type 'void Function()', but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.
  const _CustomWidget({Key key, this.cancelFunc}) : super(key: key);
                                     ^^^^^^^^^^
lib/attached_toast/attached_toast.dart:138:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:147:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:156:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:191:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:203:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:233:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:245:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:275:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:287:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:318:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:327:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/attached_toast/attached_toast.dart:336:38: Error: The argument type 'void Function(PreferDirection)' can't be assigned to the parameter type 'void Function(PreferDirection?)?' because 'PreferDirection?' is nullable and 'PreferDirection' isn't.
 - 'PreferDirection' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          onChanged: (PreferDirection value) {
                                     ^
lib/custom/custom_animation.dart:165:16: Error: The argument type 'Transform Function(BuildContext, Widget)' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget?)' because 'Widget?' is nullable and 'Widget' isn't.
 - 'Transform' is from 'package:flutter/src/widgets/basic.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/basic.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
      builder: (BuildContext context, Widget child) {
               ^
lib/custom/custom_animation.dart:215:16: Error: The argument type 'FractionalTranslation Function(BuildContext, Widget)' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget?)' because 'Widget?' is nullable and 'Widget' isn't.
 - 'FractionalTranslation' is from 'package:flutter/src/widgets/basic.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/basic.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
      builder: (BuildContext context, Widget child) {
               ^
lib/custom/custom_animation.dart:258:16: Error: The argument type 'ClipRect Function(BuildContext, Widget)' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget?)' because 'Widget?' is nullable and 'Widget' isn't.
 - 'ClipRect' is from 'package:flutter/src/widgets/basic.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/basic.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
      builder: (BuildContext context, Widget child) {
               ^
lib/custom/custom_widget.dart:20:19: Warning: Operand of null-aware operation '?.' has type 'void Function()' which excludes null.
                  backgroundReturn?.call();
                  ^
lib/custom/custom_widget.dart:49:19: Warning: Operand of null-aware operation '?.' has type 'void Function()' which excludes null.
                  cancel?.call();
                  ^
lib/custom/custom_widget.dart:61:19: Warning: Operand of null-aware operation '?.' has type 'void Function()' which excludes null.
                  confirm?.call();
                  ^
lib/custom/custom_widget.dart:110:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/custom/custom_widget.dart:120:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/custom/custom_widget.dart:130:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/custom/custom_widget.dart:182:16: Error: The argument type 'FractionalTranslation Function(BuildContext, Widget)' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget?)' because 'Widget?' is nullable and 'Widget' isn't.
 - 'FractionalTranslation' is from 'package:flutter/src/widgets/basic.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/basic.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
      builder: (BuildContext context, Widget child) {
               ^
lib/loading/custom_loading.dart:199:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/loading/custom_loading.dart:209:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/loading/custom_loading.dart:219:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/loading/loading.dart:100:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/loading/loading.dart:110:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/loading/loading.dart:120:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/custom_notification.dart:128:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/custom_notification.dart:138:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/custom_notification.dart:148:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/simple_notification.dart:129:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/simple_notification.dart:141:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/simple_notification.dart:153:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/notification.dart:101:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/notification.dart:111:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/notification/notification.dart:121:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/text/custom_text.dart:131:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/text/custom_text.dart:141:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/text/custom_text.dart:151:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/text/text.dart:116:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/text/text.dart:126:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/text/text.dart:136:48: Error: A value of type 'Object?' can't be assigned to a variable of type 'BackButtonBehavior'.
 - 'Object' is from 'dart:core'.
 - 'BackButtonBehavior' is from 'package:bot_toast/src/basis.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/basis.dart').
                          backButtonBehavior = value;
                                               ^
lib/custom/custom_animation.dart:151:21: Error: Field 'animation' should be initialized because its type 'Animation<double>' doesn't allow null.
 - 'Animation' is from 'package:flutter/src/animation/animation.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation.dart').
  Animation<double> animation;
                    ^^^^^^^^^
lib/custom/custom_animation.dart:195:17: Error: Field 'tweenOffset' should be initialized because its type 'Tween<Offset>' doesn't allow null.
 - 'Tween' is from 'package:flutter/src/animation/tween.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/tween.dart').
 - 'Offset' is from 'dart:ui'.
  Tween<Offset> tweenOffset;
                ^^^^^^^^^^^
lib/custom/custom_animation.dart:197:21: Error: Field 'animation' should be initialized because its type 'Animation<double>' doesn't allow null.
 - 'Animation' is from 'package:flutter/src/animation/animation.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation.dart').
  Animation<double> animation;
                    ^^^^^^^^^
lib/custom/custom_animation.dart:240:21: Error: Field 'animation' should be initialized because its type 'Animation<double>' doesn't allow null.
 - 'Animation' is from 'package:flutter/src/animation/animation.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation.dart').
  Animation<double> animation;
                    ^^^^^^^^^
lib/custom/custom_widget.dart:160:17: Error: Field 'tweenOffset' should be initialized because its type 'Tween<Offset>' doesn't allow null.
 - 'Tween' is from 'package:flutter/src/animation/tween.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/tween.dart').
 - 'Offset' is from 'dart:ui'.
  Tween<Offset> tweenOffset;
                ^^^^^^^^^^^
lib/custom/custom_widget.dart:161:17: Error: Field 'tweenScale' should be initialized because its type 'Tween<double>' doesn't allow null.
 - 'Tween' is from 'package:flutter/src/animation/tween.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/tween.dart').
  Tween<double> tweenScale;
                ^^^^^^^^^^
lib/custom/custom_widget.dart:163:21: Error: Field 'animation' should be initialized because its type 'Animation<double>' doesn't allow null.
 - 'Animation' is from 'package:flutter/src/animation/animation.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation.dart').
  Animation<double> animation;
                    ^^^^^^^^^
lib/loading/custom_loading.dart:16:23: Error: Field 'animationController' should be initialized because its type 'AnimationController' doesn't allow null.
 - 'AnimationController' is from 'package:flutter/src/animation/animation_controller.dart' ('/C:/src/flutter/packages/flutter/lib/src/animation/animation_controller.dart').
  AnimationController animationController;
                      ^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by MMMzq** [comment]
What is your flutter version?
