### ISSUE TITLE
Always displayed BotToast

### ISSUE THREAD

**Issue by aytunch** [MMMzq/bot_toast#127]
The `duration` we set has to be a limited time.
In our app, we need to show a toast which stays forever on screen until the user dismisses/cancels it

So I have to give `Duration(hour:100)`

But this does not seem nice.

maybe a bool field like `alwaysShow` can be added?

**Comment by MMMzq** [comment]
exapmle: 
```dart
BotToast.showText(duration:null)
```

**Comment by aytunch** [comment]
Thank you for this information
I would be nice to add it to the readme
