### ISSUE TITLE
How to use it with MaterialApp.router constructor

### ISSUE THREAD

**Issue by diegopq** [MMMzq/bot_toast#129]
**Describe the bug**
It cannot be used with MaterialApp.router as it does not have the navigatorObservers property so it cannot be initialized

**To Reproduce**
Change MaterialApp to MaterialApp.router

**Expected behavior**
Can be initialized with MaterialApp.router

**Version (please complete the following information):**
 - Flutter Version: v2.10.3
 - OS: iOS/Android
 - BotToast Version : 4.0.1

**Comment by TareqAmenahDev** [comment]
Same issue here

**Comment by lyf571321556** [comment]
Same issue here

**Comment by hwh97** [comment]
In my case the Nav2 routerDelegate usually creates a **Navigator** widget, you can add observers by passing your own navigation observer when creating the delegate.

> **Describe the bug** It cannot be used with MaterialApp.router as it does not have the navigatorObservers property so it cannot be initialized
> 
> **To Reproduce** Change MaterialApp to MaterialApp.router
> 
> **Expected behavior** Can be initialized with MaterialApp.router
> 
> **Version (please complete the following information):**
> 
> * Flutter Version: v2.10.3
> * OS: iOS/Android
> * BotToast Version : 4.0.1

**Comment by xiyionxiong** [comment]
try like this.


<img width="911" alt="image" src="https://user-images.githubusercontent.com/14977994/168247825-9d4767dd-fd83-46f3-8d98-4aa895013702.png">

**Comment by MMMzq** [comment]
For the following reasons:

1. Flutter navigator 2.0 does not uniformly provide parameters similar to NavigatorObserver.
2. Everyone's RouterDelegate implementation may be different.

So BotToast will not directly provide support for Flutter navigator 2.0 unless there are new developments about Flutter navigator 2.0.

However, most RouterDelegate implementations will provide the NavigatorObserver parameter (eg: go_router)
A simple example:
```dart
  final GoRouter _router = GoRouter(
    observers: [BotToastNavigatorObserver()],
    routes: <GoRoute>[
      ...
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      builder: BotToastInit(),
      title: 'BotToast Demo',
      routerDelegate: _router.routerDelegate,
      routeInformationParser: _router.routeInformationParser,
    );
  }
```
