### ISSUE TITLE
你好，我使用flutter web用你的toast报错

### ISSUE THREAD

**Issue by chkkassd** [MMMzq/bot_toast#13]
我的flutter sdk是dev的1.10.14，引入你的库会报错Error compiling dartdevc module:bot_toast|lib/bot_toast.ddc.js
这个该如何解决

**Comment by MMMzq** [comment]
你可以试试`master channel`,同样也支持Web
并且我这边CI测试能看到是能web build是成功的: [web build](https://github.com/MMMzq/bot_toast/runs/286915730)

这个问题之前已经遇到过,应该是和flutter有关的,有时候我没有格式化就会编译出错,多一行注释也会报错.我当时都快弄的吐血了😥

**Comment by MMMzq** [comment]
移动到 [#14]
