### ISSUE TITLE
Flutter 3.0 : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by nEdAy** [MMMzq/bot_toast#133]
**Describe the bug**

Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

**Version (please complete the following information):**
 - Flutter Version: Flutter 3.0.0 • channel stable
 - OS: Android
 - BotToast Version : 4.0.1

**Comment by vanlooverenkoen** [comment]
It is already fixed in master. So we will be using a master git import

@MMMzq is it possible to create a new pub.dev release?

**Comment by sunnykinger** [comment]
yes please release update for this plugin with this fix.

**Comment by chhinsras** [comment]
> using

how to use that way?

**Comment by shahidgeek** [comment]
/../../development/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/bot_toast_manager.dart:6:20: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
  SchedulerBinding.instance!.addPostFrameCallback((_)

**Comment by vanlooverenkoen** [comment]
Use a git dependency for now
```
  bot_toast:
    git:
      url: git@github.com:MMMzq/bot_toast.git
      ref: 8d4535073aa56578409e31c243f485e4517f40e4
```

**Comment by chhinsras** [comment]
> ref: 8d4535073aa56578409e31c243f485e4517f40e4

I had to use this instead.

bot_toast:
    git:
      url: https://github.com/MMMzq/bot_toast.git
      ref: 8d4535073aa56578409e31c243f485e4517f40e4

**Comment by vanlooverenkoen** [comment]
That should be exactly the same.=

**Comment by MMMzq** [comment]
Processing

**Comment by MMMzq** [comment]
4.0.2 Released

**Comment by chhinsras** [comment]
> 4.0.2 Released

Work!
