### ISSUE TITLE
bugs after upgrade to flutter 3.0

### ISSUE THREAD

**Issue by MohammedErbia** [MMMzq/bot_toast#135]
what I reserve  

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window-0.1.1+1/lib/src/widgets/mouse_state_builder.dart:60:30: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                             ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/bot_toast_init.dart:15:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/bot_toast_manager.dart:6:20: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/scheduler/binding.dart').
  SchedulerBinding.instance!.addPostFrameCallback((_) {
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/bot_toast_manager.dart:9:20: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/scheduler/binding.dart').
  SchedulerBinding.instance!.ensureVisualUpdate();
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/keyboard_visibility.dart:21:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-4.0.1/lib/src/keyboard_visibility.dart:37:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.4.0+1/lib/utils/utils.dart:873:41: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    final focusManager = WidgetsBinding.instance!.focusManager;
                                        ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.4.0+1/lib/utils/utils.dart:880:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.4.0+1/lib/utils/utils.dart:882:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.focusManager
                   ^

 **Version (more information here):**
 - Flutter Version:
 Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (9 days ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

 - OS: Flutter web
 - BotToast Version : bot_toast: ^4.0.1

**Comment by MMMzq** [comment]
4.0.2 Released

**Comment by MohammedErbia** [comment]
thank you
