### ISSUE TITLE
AssetNotFoundException: bot_toast|lib/bot_toast.ddc.js    

### ISSUE THREAD

**Issue by lyf571321556** [MMMzq/bot_toast#14]
AssetNotFoundException: bot_toast|lib/bot_toast.ddc.js    
![image](https://user-images.githubusercontent.com/2295872/68360022-3d46f900-0159-11ea-871c-af697f603818.png)

**Comment by MMMzq** [comment]
@lyf571321556  
这个是flutter编译本身的问题,不是我不想解决😂,是解决了后面格式化一下可能又会出现编译失败,并且我看到ci编译example的Web版本是可以的。
等flutter web进入`stable channel`，我会再尝试去解决，现在不是很推荐使用在web上使用,现在并不是很不稳定
谢谢

**Comment by lyf571321556** [comment]
> @lyf571321556
> 这个是flutter编译本身的问题,不是我不想解决😂,是解决了后面格式化一下可能又会出现编译失败,并且我看到ci编译example的Web版本是可以的。
> 等flutter web进入`stable channel`，我会再尝试去解决，现在不是很推荐使用在web上使用,现在并不是很不稳定
> 谢谢

你CI上编译的flutter编译器版本多少 能够告知下。。。

**Comment by MMMzq** [comment]
@lyf571321556 
[点击web-build->Setup flutter](https://github.com/MMMzq/bot_toast/runs/286915730)

**Comment by MMMzq** [comment]
@lyf571321556  
你可以尝试一下build [examle](https://github.com/MMMzq/bot_toast/tree/master/example) 的web版本看看能否成功吗？

**Comment by lyf571321556** [comment]
> @lyf571321556
> 你可以尝试一下build [examle](https://github.com/MMMzq/bot_toast/tree/master/example) 的web版本看看能否成功吗？



> @lyf571321556
> 你可以尝试一下build [examle](https://github.com/MMMzq/bot_toast/tree/master/example) 的web版本看看能否成功吗？

嗯，给官方提了issues，他们已经承认是编码问题 将会在近期解决 。

**Comment by lyf571321556** [comment]
[#39271](https://github.com/dart-lang/sdk/issues/39271)

**Comment by MMMzq** [comment]
非常感谢帮我提issues

如果此改动被合并进flutter我会进一步跟进,谢谢。

**Comment by chkkassd** [comment]
我发现是这样的，我在本地debug跑，或者，flutter run -d chrome,都会报错，但是，我直接flutter build web,你的toast也是可以用的，没有问题，只是苦了调试的时候，必须把你的库全部注释调才行，报的是dart lang编译错误

**Comment by MMMzq** [comment]
这个就是dart编译的问题,我当时调试的时候也纳闷为什么注释也会导致编译失败😂

**Comment by lyf571321556** [comment]
> 这个就是dart编译的问题,我当时调试的时候也纳闷为什么注释也会导致编译失败😂

官方发布的master最新版本已经解决了 这个编译问题 ，正常可以编译通过了，但是有新的问题，使用bottoast.show()报错Another exception was thrown: NoSuchMethodError: invalid member on null: 'currentState'

**Comment by MMMzq** [comment]
你好,我这边切换到`master channal` 能正常运行`example`

我的版本:
```
Flutter 1.11.1-pre.49 • channel master • https://github.com/flutter/flutter.git
Framework • revision c90d64b619 (9 hours ago) • 2019-11-14 01:16:17 -0500
Engine • revision 7c2a4ec97f
Tools • Dart 2.7.0
```
运行的命令:
`flutter run -d chrome`

**Comment by MMMzq** [comment]
@lyf571321556 
请问有日志吗？

**Comment by lyf571321556** [comment]
@MMMzq  


![截屏2019-11-1621 05 35](https://user-images.githubusercontent.com/2295872/68993615-186b2800-08b5-11ea-8811-38d4371e8d67.png)

**Comment by MMMzq** [comment]
@lyf571321556 
看了一下日志:发现是`await _initCompleter.future`报的错.
不过我这边我看了一下代码,`_initCompleter`基本上不可能为`null`,所以我觉得flutter还有bug导致的？

或者你可以在你本地运行一下`example`的`web`看看是否能正常运行,对比参照一下好排除问题。

**Comment by lyf571321556** [comment]
@MMMzq 嗯 不是太稳定 ，等release版本再看吧  最近发版比较频繁

**Comment by seeyou888999** [comment]
BotToast.showCustomLoading 自定义 的情况下 如何传递 loadWidget ? 如果不传递则报错 。 文档上面也写的不太清楚。建议作者对自定义这块能详细描述下 如何使用

**Comment by MMMzq** [comment]
@seeyou888999 
你可以看一下[example](https://github.com/MMMzq/bot_toast/blob/master/example/lib/loading/custom_loading.dart),里面有一个例子是使用`BotToast.showCustomLoading`方法的

**Comment by seeyou888999** [comment]
挺奇怪的 我什么也没做 正常使用 BotToast.showText 可以使用 但是使用 BotToast.showCustomLoading(
                        align: Alignment.center,
                        crossPage: true,
                        toastBuilder: (cancelFunc) {
                          return Text('123');
                      })；  这种方式就报错 。。我查看你的example 能正常运行。这就搞不懂是哪里的问题了 。。
这是报错代码  
loadWidget not null
'package:bot_toast/src/toast.dart':
Failed assertion: line 484 pos 12: 'ackgroundColor = Col'

**Comment by MMMzq** [comment]
@seeyou888999 
请把代码和完整日志贴上来,谢谢.

**Comment by MMMzq** [comment]
```dart
BotToast.showCustomLoading(
align: Alignment.center,
crossPage: true,
toastBuilder: (cancelFunc) {
return Text('123');
})；
```
这个代码是能运行的，你可能需要仔细检查是不是别的问题

**Comment by MMMzq** [comment]
@lyf571321556 
升级到`2.2.0`版本应该就可以了

**Comment by MMMzq** [comment]
如有问题可重新打开
