### ISSUE TITLE
与flutterboost混合使用，路由观察无用

### ISSUE THREAD

**Issue by freedoem** [MMMzq/bot_toast#150]
Widget appBuilder(Widget home) {
    // bool v = widget.value ?? false;
    // String l=widget.local?? 'zh';
    final botToastBuilder = BotToastInit();
    return MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => LocalProvider())],
      child: Consumer<LocalProvider>(
        builder: (_, LocalProvider localProvider, child) {
      //  var v=    AppStore.getV()??false;
          return MaterialApp(
              home: home,
              debugShowCheckedModeBanner: true,
              builder: (context,__) {
                child = MediaQuery(
                  data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                  child: home,
                );
                child = botToastBuilder(context,child);
                return  child!;
              },
              navigatorObservers: [BotToastNavigatorObserver()],
              localizationsDelegates: const [
                GlobalMaterialLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                S.delegate
              ],
              supportedLocales: S.delegate.supportedLocales,
              locale: localProvider.locale
          );
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return FlutterBoostApp(
      routeFactory,
      appBuilder: appBuilder,
    );
  }

**Comment by MMMzq** [comment]
参考这，注意BotToastInit调用的位置。

```dart
//Warning: Don't arbitrarily adjust the position of calling the BotToastInit function 
final botToastBuilder = BotToastInit();  //1. call BotToastInit 
MaterialApp(
      title: 'BotToast Demo',
      builder: (context, child) {
        child = myBuilder(context,child);  //do something
        child = botToastBuilder(context,child); 
        return child;
      }, 
      navigatorObservers: [BotToastNavigatorObserver()], //2. registered route observer
      home: XxxxPage(),
  )
```
