### ISSUE TITLE
showCustomLoading leads to _AssertionError

### ISSUE THREAD

**Issue by YDA93** [MMMzq/bot_toast#152]
**Describe the bug**
<details>
<summary>Stack Trace</summary>

```

flutter: 'package:bot_toast/src/toast_navigator_observer.dart': Failed assertion: line 35 pos 12: 'debugInitialization':     Please initialize!
toast_navigator_observer.dart:35
    Example:
    BotToastInit(
      child:MaterialApp(
      title: 'Xxxx Demo',
      navigatorObservers: [BotToastNavigatorObserver()],
      home: XxxxPage(),
    ));
flutter:
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      BotToastNavigatorObserver.register
toast_navigator_observer.dart:35

```
</details>

**To Reproduce**
1. Run showCustomLoading
2. See error

**Expected behavior**
showCustomLoading should be working just fine

**Version:**
 - Flutter Version: 3.10.3
 - OS: iOS
 - BotToast Version : ^4.0.4

**Additional context**
Switching to showLoading works, but showCustomLoading leads to this error.
I already initialized the plugin as per documentation except I don't use navigation observers.

**Comment by MMMzq** [comment]
This is a defensive check. If the parameter "crossPage" is set to true, it is necessary to also set "BotToastNavigatorObserver()" for it to take effect. I recommend always setting "BotToastNavigatorObserver()".

**Comment by MMMzq** [comment]
If crossPage is false, `BotToastNavigatorObserver.register` will be called.


https://github.com/MMMzq/bot_toast/blob/95467f4637575c22caef0643e12953e7be2b5bde/lib/src/toast.dart#L801-L805
