### ISSUE TITLE
MaterialApp.router with auto_route with botToastBuilder triggers aditional page to push on WidgetInspector toggle

### ISSUE THREAD

**Issue by Skleprozzz** [MMMzq/bot_toast#153]
Hello, I am using auto_route 7.7.0 with bot_toast: ^4.0.4,

My use case is pretty simple:
final _appRouter = AppRouter();
MaterialApp.router(
          routerConfig: _appRouter.config(
            navigatorObservers: () => [BotToastNavigatorObserver()],
          ),
          builder: BotToastInit()
)

and then I trying to toggle "select widget mode" whole navigation stack rebuilds and pushes again

I think that problem is inside botToastBuilder

Can you help please?

**Comment by MMMzq** [comment]
Is there a demo that can reproduce this issue?
