### ISSUE TITLE
希望增加一个全局配置

### ISSUE THREAD

**Issue by 211277729** [MMMzq/bot_toast#154]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**

**Comment by MMMzq** [comment]
4.1 版本已支持全局配置
