### ISSUE TITLE
在BotToast.showAttachedWidget中使用textField会导致窗口消失

### ISSUE THREAD

**Issue by E-Trent** [MMMzq/bot_toast#161]
BotToast.showAttachedWidget的build中 放入一个textField。如果聚焦textField弹起软键盘。就会导致整个弹出的组件消失。
抱歉 因为环境特殊没有办法很舒适的使用编辑器来舒适的创建demo代码，如果您无法理解我遇到的问题请回复我，我会尝试去一个可以使用编辑器的环境给到你代码。

**Comment by MMMzq** [comment]
https://github.com/MMMzq/bot_toast/issues/71
你可以先参考这个解决方式试一下、看看能不能解决。

**Comment by E-Trent** [comment]
> #71 你可以先参考这个解决方法试一下、看看能否解决。

感谢你的回复，提问之前已经尝试过这个方案了，实际上我为了实现我的布局已经包裹了Overlay和OverlayEntry。我同时尝试了showAttachedWidget中的所有属性。都无法解决。

**Comment by MMMzq** [comment]
那可能你最好写一个可以复现的demo。

**Comment by E-Trent** [comment]
`import 'package:bot_toast/bot_toast.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
      builder: BotToastInit(),
      navigatorObservers: [BotToastNavigatorObserver()],
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SizedBox(
        height: double.infinity,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.start,
          mainAxisSize: MainAxisSize.max,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            LeftButtons(),
          ],
        ),
      ),
    );
  }
}

class LeftButtons extends StatelessWidget {
  const LeftButtons({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 300,
      color: Colors.black,
      padding: const EdgeInsets.all(10),
      child: Column(
        children: [
          GestureDetector(
            onTap: () {
              BotToast.showAttachedWidget(
                attachedBuilder: (_) {
                  return Material(
                    child: Container(
                      color: Colors.black,
                      height: 300,
                      width: 200,
                      child: const TextField(
                        decoration: InputDecoration(
                          fillColor: Colors.white,
                          filled: true,
                        ),
                      ),
                    ),
                  );
                },
                targetContext: context,
                horizontalOffset: 10.0,
                preferDirection: PreferDirection.leftCenter,
              );
            },
            child: iconWidget(),
          ),
          const SizedBox(
            height: 15,
          ),
          iconWidget(),
          const SizedBox(
            height: 15,
          ),
          iconWidget(),
          const SizedBox(
            height: 15,
          ),
          iconWidget(),
        ],
      ),
    );
  }

  Widget iconWidget() {
    return const Column(
      children: [
        Icon(
          Icons.ac_unit_outlined,
          color: Colors.white,
          size: 30,
        ),
        Text(
          "标签",
          style: TextStyle(fontSize: 16, color: Colors.white),
        ),
      ],
    );
  }
}
`
运行平台:android
运行设备:android模拟器 (横向)
flutter版本:3.13.6
操作逻辑:左侧有一个竖排的按钮组 ，第一个按钮可以被点击唤醒AttachedWidget。出现的黑色容器最上方有一个很不显眼的TextField。点击后唤醒软键盘，AttachedWidget就会消失。

**Comment by E-Trent** [comment]
> 那可能你最好写一个可以复现的demo。

`import 'package:bot_toast/bot_toast.dart';
import 'package:flutter/material.dart';

void main() {
runApp(const MyApp());
}

class MyApp extends StatelessWidget {
const MyApp({super.key});

@OverRide
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
),
home: MyHomePage(),
builder: BotToastInit(),
navigatorObservers: [BotToastNavigatorObserver()],
);
}
}

class MyHomePage extends StatelessWidget {
const MyHomePage({super.key});

@OverRide
Widget build(BuildContext context) {
return const Scaffold(
body: SizedBox(
height: double.infinity,
child: Row(
mainAxisAlignment: MainAxisAlignment.start,
mainAxisSize: MainAxisSize.max,
crossAxisAlignment: CrossAxisAlignment.center,
children: [
LeftButtons(),
],
),
),
);
}
}

class LeftButtons extends StatelessWidget {
const LeftButtons({Key? key}) : super(key: key);

@OverRide
Widget build(BuildContext context) {
return Container(
height: 300,
color: Colors.black,
padding: const EdgeInsets.all(10),
child: Column(
children: [
GestureDetector(
onTap: () {
BotToast.showAttachedWidget(
attachedBuilder: (_) {
return Material(
child: Container(
color: Colors.black,
height: 300,
width: 200,
child: const TextField(
decoration: InputDecoration(
fillColor: Colors.white,
filled: true,
),
),
),
);
},
targetContext: context,
horizontalOffset: 10.0,
preferDirection: PreferDirection.leftCenter,
);
},
child: iconWidget(),
),
const SizedBox(
height: 15,
),
iconWidget(),
const SizedBox(
height: 15,
),
iconWidget(),
const SizedBox(
height: 15,
),
iconWidget(),
],
),
);
}

Widget iconWidget() {
return const Column(
children: [
Icon(
Icons.ac_unit_outlined,
color: Colors.white,
size: 30,
),
Text(
"标签",
style: TextStyle(fontSize: 16, color: Colors.white),
),
],
);
}
}
`
运行平台:android
运行设备:android模拟器 (横向)
flutter版本:3.13.6
操作逻辑:左侧有一个竖排的按钮组 ，第一个按钮可以被点击唤醒AttachedWidget。出现的黑色容器最上方有一个很不显眼的TextField。点击后唤醒软键盘，AttachedWidget就会消失。

**Comment by E-Trent** [comment]
> 也许你最好写一个可以复述的演示。

我尝试着在AttachedWidget中放入按钮，点击后showAnimationWidget()  我在新弹出的widget中放入了TextField，点击后AttachedWidget依旧会消失

**Comment by MMMzq** [comment]
https://github.com/MMMzq/bot_toast/issues/71#issuecomment-657915933
你再用Overlay包装一下就能正常工作了

**Comment by E-Trent** [comment]
> [#71（评论）](https://github.com/MMMzq/bot_toast/issues/71#issuecomment-657915933) 你再用Overlay包装一下就能正常工作了

刚刚我在toastBuilder中  已经对组件进行了Material->Overlay->OverlayEntry的包裹   但是唤醒软键盘之后 AttachedWidget依旧会消失。
![image](https://github.com/MMMzq/bot_toast/assets/58932733/ef74f6ea-e5fa-45ec-98ef-64a75a46bc1e)
非常抱歉  因为环境特殊  只能用截图了

**Comment by MMMzq** [comment]
这是因为showAttachedWidget在弹出键盘时会自动调用cancel方法关闭弹窗，这么做的原因是因为使用`target`参数（绝对坐标）时，如果键盘弹出不关闭弹窗的话会出现位置错误或者被遮挡。
<img width="703" alt="image" src="https://github.com/MMMzq/bot_toast/assets/28224568/b1ab58c4-9163-4748-816d-d9e42932781c">

建议你使用路由的方式去做，不建议你showAttachedWidget弹出一个TextField，到导致出现很多奇怪的问题。
