### ISSUE TITLE
How do I set the height offset?

### ISSUE THREAD

**Issue by wp993080086** [MMMzq/bot_toast#165]
**Describe the bug**

I have a custom Loading Widget, but it is always centered horizontally and vertically. How do I set it to center horizontally and vertical to 200?

**To Reproduce**
```
BotToast.showCustomLoading(
    clickClose: true,
    backgroundColor: Colors.black.withOpacity(0.8),
    toastBuilder: (cancelFunc) {
      return MyLoading();
    },
  );
```

**Version (please complete the following information):**
 - bot_toast: ^4.1.3
 - flutter 3.x

**Comment by MMMzq** [comment]
```dart
BotToast.showCustomLoading(
    clickClose: true,
    align: Alignment.center,
    backgroundColor: Colors.black.withOpacity(0.8),
    toastBuilder: (cancelFunc) {
      return MyLoading();
    },
  );
```

**Comment by wp993080086** [comment]
> ```dart
> BotToast.showCustomLoading(
>     clickClose: true,
>     align: Alignment.center,
>     backgroundColor: Colors.black.withOpacity(0.8),
>     toastBuilder: (cancelFunc) {
>       return MyLoading();
>     },
>   );
> ```

I want it to be centered horizontally, vertical =200, and yours is centered vertically and horizontally

**Comment by MMMzq** [comment]
```dart
    BotToast.showCustomLoading(
      clickClose: true,
      align: Alignment.topCenter,
      backgroundColor: Colors.black.withOpacity(0.8),
      toastBuilder: (cancelFunc) {
        return Padding(
          padding: const EdgeInsets.only(top: 200),
          child: MyLoading(),
        );
      },
    );
```
