### ISSUE TITLE
When returning to previous page there is an onBlur simultaneous presence causing conflict issues

### ISSUE THREAD

**Issue by laterdayi** [MMMzq/bot_toast#168]
**Describe the bug**
When returning to previous page there is an onBlur simultaneous presence causing conflict issues

**To Reproduce**

When I go from page a to page b, I have a focus to the input box. When I lose the focus, I will be prompted whether the toast is empty. If I directly click on appbar to return to page a, toast will be displayed on page A

This is not the desired effect, I want to show toast only on the b page, I set the cross page but it doesn't work

**Comment by MMMzq** [comment]
Can you provide a demo?

**Comment by laterdayi** [comment]
https://github.com/MMMzq/bot_toast/assets/122137647/b09ca1c2-12c5-4885-b33c-92776232c0b5
What I expect is that if I click the back page, I will no longer be prompted by the previous page
  @MMMzq

**Comment by laterdayi** [comment]
https://github.com/MMMzq/bot_toast/assets/122137647/1b872097-ef0d-44d6-966e-70f77c6b1875

What I expect is that if I click the back page, I will no longer be prompted by the previous page  

@MMMzq

**Comment by MMMzq** [comment]
It looks like you are calling the API at the wrong time. Or you can provide a reproducible running demo so that I can troubleshoot the problem faster.

**Comment by laterdayi** [comment]
I have provided a minimal reproduction and hope you can help solve it

**Comment by laterdayi** [comment]
https://github.com/laterdayi/testx  

 hope you can help solve it

 @MMMzq

**Comment by MMMzq** [comment]
<img width="986" alt="image" src="https://github.com/MMMzq/bot_toast/assets/28224568/b1820c30-7c2d-4398-aefa-0be092dbf4bd">

Please initialize in this way.

https://github.com/MMMzq/bot_toast?tab=readme-ov-file#3-initialization-bottoast

**Comment by laterdayi** [comment]
![image](https://github.com/MMMzq/bot_toast/assets/122137647/1e3d39be-af5f-4443-b2ef-80f1d14e58b7)
![image](https://github.com/MMMzq/bot_toast/assets/122137647/d7ddb48e-56b5-4d77-88b3-d058d78f76f8)
It was initialized that way, but it doesn't work  @MMMzq

**Comment by MMMzq** [comment]
<img width="1010" alt="image" src="https://github.com/MMMzq/bot_toast/assets/28224568/c8d45b15-469b-46a2-8412-def69dbb0335">

**Comment by laterdayi** [comment]
After this initialization, the problem still exists

**Comment by laterdayi** [comment]
Can you help me test it in my duplicate project

**Comment by MMMzq** [comment]
This is because the onFocusChange callback is also triggered when the router detects a change

**Comment by laterdayi** [comment]
Is there a solution to this? The current user experience is not very good

**Comment by MMMzq** [comment]
```dart
                  SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
                    SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
                      Navigator.of(context).push(MaterialPageRoute(builder: (c)=>Scaffold(
                        appBar: AppBar(),
                      )));
                    });
                  });
```
Use SchedulerBinding.instance.addPostFrameCallback. Delay the push route Api call by 2 frames.

**Comment by MMMzq** [comment]
```dart            
    onPressed: () {
                  FocusScope.of(context).requestFocus(FocusNode());
                  SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
                    Navigator.of(context).push(MaterialPageRoute(builder: (c)=>Scaffold(
                      appBar: AppBar(),
                    )));
                  });

                  // Get.toNamed(Routes.login);
                },
```
or
```dart
                onFocusChange: (v) {
                  if (!v && ModalRoute.of(context)!.isCurrent) {
                    BotToast.showSimpleNotification(title: "init", crossPage: false);
                  }
                }
```
This works normally.
You can replace Get. toNamed with Navigators.

**Comment by laterdayi** [comment]
Thank you for your help, after the test, the first kind can not, the second kind is normal
