### ISSUE TITLE
桌面端显示的Toast可以移动

### ISSUE THREAD

**Issue by onism0106** [MMMzq/bot_toast#169]
![WeChatc5e6a288c37b0a7afb549394c427b4f2](https://github.com/MMMzq/bot_toast/assets/38930828/e538ea83-a5ce-4d7c-bd0f-df5630927d21)
显示Toast时，鼠标向上滑动时，这个Toast也可以跟着移动

**Comment by MMMzq** [comment]
可以的请提供一个可复现的demo

**Comment by onism0106** [comment]
```
ElevatedButton(
              onPressed: () {
                BotToast.showCustomNotification(
                  align: const Alignment(0, 0.8),
                  animationDuration: Duration.zero,
                  animationReverseDuration: Duration.zero,
                  toastBuilder: (cancelFunc) {
                    return Container(
                      width: 100,
                      height: 100,
                      alignment: Alignment.center,
                      color: Colors.red,
                      child: Text("Toast"),
                    );
                  },
                );
              },
              child: Text("Toast"),
            ),
```

上面的demo的代码，可以复现，在Mac平台上，使用Magic Mouse，上下左面扫动（不是拖拽），这个Toast可以跟随移动。
尝试添加IgnorePointer并不生效。如果特性就是这样的话，有没有方法可以禁用掉此特性？如果不是的话，可能是个bug

**Comment by onism0106** [comment]
> `ElevatedButton( onPressed: () { BotToast.showCustomNotification( align: const Alignment(0, 0.8), animationDuration: Duration.zero, animationReverseDuration: Duration.zero, toastBuilder: (cancelFunc) { return Container( width: 100, height: 100, alignment: Alignment.center, color: Colors.red, child: Text("Toast"), ); }, ); }, child: Text("Toast"), ),`
> 
> 上面的demo的代码，可以复现，在Mac平台上，使用Magic Mouse，上下左面扫动（不是拖拽），这个Toast可以跟随移动。 尝试添加IgnorePointer并不生效。如果特性就是这样的话，有没有方法可以禁用掉此特性？如果不是的话，可能是个bug

拖拽也可以复现
