### ISSUE TITLE
showText放开allowClick属性

### ISSUE THREAD

**Issue by zhangxiongwen** [MMMzq/bot_toast#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**

showText的使用场景 allowClick属性被强制设置为true, 能否放开下这个属性

**Comment by MMMzq** [comment]
你可以提个pr将这个属性开放出来
