### ISSUE TITLE
使用不了，引入项目报错，项目都运行不了；求解

### ISSUE THREAD

**Issue by laijinxian** [MMMzq/bot_toast#18]
![image](https://user-images.githubusercontent.com/30945933/68749473-42181b00-0639-11ea-9294-e5850c07439c.png)
![image](https://user-images.githubusercontent.com/30945933/68749484-47756580-0639-11ea-97e8-e802999ea7b7.png)

**Comment by MMMzq** [comment]
@laijinxian 
你是从1.x版本升级上来的吗？
建议使用`flutter clean` 再运行试一下

**Comment by laijinxian** [comment]
flutter 升级了下就可以了，谢谢
