### ISSUE TITLE
请问怎么在请求拦截器里面关闭loading，刚学基础薄弱，文档没看懂

### ISSUE THREAD

**Issue by AvnTwty** [MMMzq/bot_toast#23]

**Comment by MMMzq** [comment]
可以看 #9

**Comment by AvnTwty** [comment]
> 可以看 #9

![image](https://user-images.githubusercontent.com/22271431/70298780-b7889d00-182d-11ea-8c21-ec7766fee84e.png)可是我这样写也关不掉

**Comment by MMMzq** [comment]
@AvnTwty 
这可能是个bug.
我最近好像也发现了这个问题
你可以尝试一下
```dart 
CancelFunc cancel = BotToast.showLoading();
await Future.delayed(Duration(milliseconds: 500));
cancel();
```
这个bug好像只会在第一次弹出Toast并且show之后马上cancel才会触发

**Comment by MMMzq** [comment]
@AvnTwty 
升级到`2.2.0`版本应该就能正常关闭了

**Comment by AvnTwty** [comment]
> @AvnTwty
> 升级到`2.2.0`版本应该就能正常关闭了
升级版本后正常了，感谢帮助
