### ISSUE TITLE
The key [LabeledGlobalKey<BotToastManagerState>#1ac8b] was used by multiple widgets.

### ISSUE THREAD

**Issue by git-xbits** [MMMzq/bot_toast#25]
```
Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        StreamProvider<UserProfile>.value(
          value: locator<LoginService>().userController.stream,
          initialData: UserProfile.initial(),
        ),
        StreamProvider<MobileSettings>.value(
          value: locator<MobileSettingsService>().settingsController.stream,
          initialData: MobileSettings.initial(),
        ),
      ],
      child: DynamicTheme(
        key: dynamicKey,
          defaultBrightness: Brightness.dark,
          data: (brightness) => appThemePadrao().data,
          themedWidgetBuilder: (context, theme) {
            return  BotToastInit(
              key: botKey,
              child: MaterialApp(
                key: materialKey,
                title: 'CRM',
                debugShowCheckedModeBanner: false,
                theme: theme,
                initialRoute: '/',
                onGenerateRoute: Router.generateRoute,
                navigatorObservers: [BotToastNavigatorObserver()],
              ),
            );
          }
      ),
    );
  }
```

I  getting this error:

> 
> I/flutter ( 5336): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter ( 5336): The following assertion was thrown building ProxyDispose(state: _ProxyDisposeState#e48d3):
> I/flutter ( 5336): Multiple widgets used the same GlobalKey.
> I/flutter ( 5336): The key [LabeledGlobalKey<BotToastManagerState>#1ac8b] was used by multiple widgets. The parents of
> I/flutter ( 5336): those widgets were:
> I/flutter ( 5336): - ProxyDispose(state: _ProxyDisposeState#aeb65)
> I/flutter ( 5336): - ProxyDispose(state: _ProxyDisposeState#e48d3)
> I/flutter ( 5336): A GlobalKey can only be specified on one widget at a time in the widget tree.
> I/flutter ( 5336): 
> I/flutter ( 5336): User-created ancestor of the error-causing widget was:
> I/flutter ( 5336):   MaterialApp-[<'__materialKey__'>]
> 

> 
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale pt-BR)
>     • Flutter version 1.9.1+hotfix.6 at /Users/phelipepalte/SDK/flutter
>     • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/phelipepalte/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B53
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [!] VS Code (version 1.40.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     ✗ Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
> 
> ! Doctor found issues in 1 category.
>

**Comment by MMMzq** [comment]
You seem to be using 2.0 version , so you may need to upgrade to the latest version, and version 2.2 has been removed `BotToastInit.key`, `BotToastInit` requires managing GlobalKey yourself

**Comment by git-xbits** [comment]
> You seem to be using 2.0 version , so you may need to upgrade to the latest version, and version 2.2 has been removed `BotToastInit.key`, `BotToastInit` requires managing GlobalKey yourself

x.x

I dont believe I make this mistake.. lol

Thank you. Unfortunatey when I open this issue I don't check the versions.

I'll close the issue now.
