### ISSUE TITLE
建议增加通知背景颜色

### ISSUE THREAD

**Issue by gitfornncn** [MMMzq/bot_toast#26]
项目中有用到通知showSimpleNotification，但看了下无法更改背景颜色，
下一版本可否增加下。非常感谢您的付出

**Comment by MMMzq** [comment]
@gitfornncn 
1. 我建议新建一个在`BotToast`基础上封装的一个`Toast`工具类
2. 此工具类可以直接使用`showCustomNotification`方法来进行样式的定制已达到定制背景颜色的目的(可以直接参考`showNotification`方法,`showNotification`其实就是直接使用`Card`+`ListTile`,代码很简单)
3. `Toast`的工具类可以给你以后更大程度上的灵活性比如:`同一修改样式`,`测试时修改Toast行为以便测试`等等
4. `showSimpleNotification`和`showNotification`都是一些基本样式,如果样式不符合要求时都可以使用`showCustomXxx`方法来达到更好控制样式的目的 ,这也是`showCustomXxx`方法存在的目的.😉

**Comment by gitfornncn** [comment]
> @gitfornncn
> 
> 1. 我建议新建一个在`BotToast`基础上封装的一个`Toast`工具类
> 2. 此工具类可以直接使用`showCustomNotification`方法来进行样式的定制已达到定制背景颜色的目的(可以直接参考`showNotification`方法,`showNotification`其实就是直接使用`Card`+`ListTile`,代码很简单)
> 3. `Toast`的工具类可以给你以后更大程度上的灵活性比如:`同一修改样式`,`测试时修改Toast行为以便测试`等等
> 4. `showSimpleNotification`和`showNotification`都是一些基本样式,如果样式不符合要求时都可以使用`showCustomXxx`方法来达到更好控制样式的目的 ,这也是`showCustomXxx`方法存在的目的.😉

非常感谢。
