### ISSUE TITLE
性能上希望可以再优化一下

### ISSUE THREAD

**Issue by qcdys** [MMMzq/bot_toast#30]

**Comment by qcdys** [comment]
![5771582779807_ pic_hd](https://user-images.githubusercontent.com/15402976/75413873-c4ff8000-5961-11ea-87f8-92a886776f03.jpg)

**Comment by MMMzq** [comment]
@qcdys 
我是用Example的`showLoading`(并运行20s)来测试

测试机型: 小米9se

结果如下:
#### profile模式: 稳定在60fps 
![profile测试结果](https://user-images.githubusercontent.com/28224568/75498648-b4531680-5a02-11ea-9163-bcb311cd517a.PNG)

#### debug模式: 也是稳定在60fps左右(测试了三次)  
##### 并且我打断点,也只有`CircularProgrechongzissIndicator`一直在rebuild,所以关于rebuild方面是符合预期的
##### 注意使用debug模式会影响测试结果(这个debug不是flutter的那个debug,是as运行的那个小虫子) 
![捕获](https://user-images.githubusercontent.com/28224568/75499050-c41f2a80-5a03-11ea-90a1-3f8d8601ce18.PNG)


#### 模拟器的debug模式: 首次稳定在30fps,之后再运行稳定在60fps

**Comment by MMMzq** [comment]
如果需要可重新打开
