### ISSUE TITLE
CustomWidget 点击穿透问题

### ISSUE THREAD

**Issue by IceDream1024** [MMMzq/bot_toast#31]
请问官方例子里面的 customeWidget 如何让背景黑色遮罩支持点击穿透

**Comment by IceDream1024** [comment]
尝试过设置 showAnimationWidget 的参数 allowClick ，但是无效果

**Comment by MMMzq** [comment]
@IceDream1024 你想要的是能正常点击到黑色遮罩下面的页面吗,而不是黑色遮罩关闭Toast?

**Comment by MMMzq** [comment]
@IceDream1024 

allowClick表达的是:是否允许点击事件是可以传递给到Toast下面的页面的.

那为什么设置了还没有用呢？
主要是因为点击事件冒泡的过程被更高优先级的Widget给捕获了,导致没有效果。
就拿customeWidget这个例子来说明:
```dart
BotToast.showAnimationWidget(
      clickClose: false,
      allowClick: true, //1.设置为true
      onlyOne: true,
      crossPage: true,
//2.取消使用BackgroundRoute,因为BackgroundRoute使用了PageRouteBuilder,
// 而PageRouteBuilder也会导致点击事件被捕获,有兴趣的话可以看一下Route生成遮罩那部分代码
//      wrapAnimation: (controller, cancel, child) => BackgroundRoute(
//            child: child,
//            blockPopup: blockPopup,
//            cancelFunc: cancel,
//            physicalButtonPopCallback: () {
//              physicalBackButton?.call();
//            },
//          ),
//
//把下面的GestureDetector删掉,以及使用IgnorePointer包住AnimatedBuilder
//IgnorePointer主要是把DecoratedBox的手势监听忽视掉.
//顺便提一下:如果Container使用了color参数也有类似的行为
      wrapToastAnimation: (controller, cancel, child) => Stack(
            children: <Widget>[
              IgnorePointer(
                child: AnimatedBuilder(
                  builder: (_, child) => Opacity(
                    opacity: controller.value,
                    child: child,
                  ),
                  child: DecoratedBox(
                    decoration: BoxDecoration(color: Colors.black26),
                    child: SizedBox.expand(),
                  ),
                  animation: controller,
                ),
              ),
              CustomOffsetAnimation(
                controller: controller,
                child: child,
              )
            ],
          ),
     .....
      );
```

**Comment by IceDream1024** [comment]
> @IceDream1024
> 
> allowClick表达的是:是否允许点击事件是可以传递给到Toast下面的页面的.
> 
> 那为什么设置了还没有用呢？
> 主要是因为点击事件冒泡的过程被更高优先级的Widget给捕获了,导致没有效果。
> 就拿customeWidget这个例子来说明:
> 
> ```dart
> BotToast.showAnimationWidget(
>       clickClose: false,
>       allowClick: true, //1.设置为true
>       onlyOne: true,
>       crossPage: true,
> //2.取消使用BackgroundRoute,因为BackgroundRoute使用了PageRouteBuilder,
> // 而PageRouteBuilder也会导致点击事件被捕获,有兴趣的话可以看一下Route生成遮罩那部分代码
> //不过如果取消了这部分代码会导致点击物理按钮的事件会失效
> //      wrapAnimation: (controller, cancel, child) => BackgroundRoute(
> //            child: child,
> //            blockPopup: blockPopup,
> //            cancelFunc: cancel,
> //            physicalButtonPopCallback: () {
> //              physicalBackButton?.call();
> //            },
> //          ),
> //
> //3.把下面的GestureDetector删掉(我这里是已经删掉了),以及使用IgnorePointer包住AnimatedBuilder
> //IgnorePointer主要是把DecoratedBox的手势监听忽视掉.
> //顺便提一下:如果Container使用了color参数也有类似的行为
>       wrapToastAnimation: (controller, cancel, child) => Stack(
>             children: <Widget>[
>               IgnorePointer(
>                 child: AnimatedBuilder(
>                   builder: (_, child) => Opacity(
>                     opacity: controller.value,
>                     child: child,
>                   ),
>                   child: DecoratedBox(
>                     decoration: BoxDecoration(color: Colors.black26),
>                     child: SizedBox.expand(),
>                   ),
>                   animation: controller,
>                 ),
>               ),
>               CustomOffsetAnimation(
>                 controller: controller,
>                 child: child,
>               )
>             ],
>           ),
>      .....
>       );
> ```

感谢，我就是想达到这种效果
