### ISSUE TITLE
BotToast.showText

### ISSUE THREAD

**Issue by huangred** [MMMzq/bot_toast#33]
默认传递text是string，且在TextToast中设置了textAlign=TextAlign.center，如果显示内容较多，第二行不是左对齐，而是居中了，建议增加textAlign属性。
或者增加一个textwidget属性，允许完全自定义显示格式。
text和textwidget可以二选一。

**Comment by MMMzq** [comment]
@huangred 
如果`showText`不满足需求,可以使用`showCustomText`进行定制,前者也只是把后者封装了一次

**Comment by huangred** [comment]
@MMMzq 谢谢提醒

**Comment by MMMzq** [comment]
如有问题可重新打开
