### ISSUE TITLE
Opening dropdown causing error

### ISSUE THREAD

**Issue by mocodesmo** [MMMzq/bot_toast#34]
Hello,

When i add a dropdown widget inside bot_toast widget and i click on the dropdown, i get '_dropdownRoute == null' error. 
The dropdown options actually open behind the bot_toast widget, which i can see after closing the bot_toast widget.

Is there any way to fix this?

Thank you for your time.

**Comment by MMMzq** [comment]
I haven't encountered this error.
If you can provide an example, I will try to help you solve it

**Comment by mocodesmo** [comment]
void main() {
  runApp(BotToastInit(
      child: MaterialApp(
          navigatorObservers: [BotToastNavigatorObserver()],
          home: Scaffold(
              body: RaisedButton(
                  child: Text('click'),
                  onPressed: () {
                    BotToast.showWidget(toastBuilder: (_) {
                      return Scaffold(
                          body: Column(children: <Widget>[
                        DropdownButton<String>(
                          items: [
                            DropdownMenuItem(child: Text('one')),
                            DropdownMenuItem(child: Text('two')),
                            DropdownMenuItem(child: Text('thre')),
                            DropdownMenuItem(child: Text('four')),
                          ],
                          onChanged: (n) {},
                        ),
                        RaisedButton(
                            child: Text('close'),
                            onPressed: () {
                              BotToast.cleanAll();
                            })
                      ]));
                    });
                  })))));
}

**Comment by MMMzq** [comment]
The following code works fine

```dart
void main() {
  runApp(BotToastInit(
      child: MaterialApp(
          navigatorObservers: [BotToastNavigatorObserver()],
          home: Scaffold(
              body: Container(
            margin: EdgeInsets.only(top: 17),
            child: Builder(
              builder: (_) => RaisedButton(
                  child: Text('click'),
                  onPressed: () {
                    BotToast.showWidget(toastBuilder: (cancel) {
                      return Center(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            Material(
                              child: DropdownButton(
                                items: [
                                  DropdownMenuItem(child: Text('one')),
                                  DropdownMenuItem(child: Text('two')),
                                  DropdownMenuItem(child: Text('thre')),
                                  DropdownMenuItem(child: Text('four')),
                                ],
                                onChanged: (n) {},
                              ),
                            ),
                            RaisedButton(
                              onPressed: () {
                                cancel();
                              },
                              child: Text('close'),
                            )
                          ],
                        ),
                      );
                    });
                  }),
            ),
          )))));
}

```

**Comment by MMMzq** [comment]
It is worth noting: Toast is always on the ordinary page
