### ISSUE TITLE
showSimpleNotification 希望加一个onCancel事件

### ISSUE THREAD

**Issue by LeiQiao** [MMMzq/bot_toast#35]
希望在 Notification 系列的组件上侧滑或点击关闭按钮时加一个onCancel的事件，谢谢！

**Comment by MMMzq** [comment]
@LeiQiao 
添加一个Toast的onDispose事件可以吗

**Comment by LeiQiao** [comment]
不是特别熟悉您的代码，只要能满足功能即可，我现在是这么做的，直接用的最里面的方法，复写了 slideOffFunc 方法


CancelFunc notification({
  String title,
  String subTitle,
  Color backgroundColor=Colors.white,
  bool onlyOne=true,
  Duration duration,
  VoidCallback onTap,
  VoidCallback onCancel
}) {
  List<DismissDirection> dismissDirections = const [
    DismissDirection.horizontal,
    DismissDirection.up
  ];
  return BotToast.showAnimationWidget(
      crossPage: true,
      allowClick: true,
      clickClose: false,
      ignoreContentClick: false,
      onlyOne: onlyOne,
      duration: duration ?? Duration(seconds: 2),
      animationDuration: const Duration(milliseconds: 256),
      wrapToastAnimation: (controller, cancel, child) {
        return SafeArea(child: notificationAnimation(controller, cancel, child));
      },
      toastBuilder: (cancelFunc) =>
        NotificationToast(
          child: Card(
            child: ListTile(
              onTap: onTap,
              title: Text(title),
              subtitle: Text(subTitle)
            )
          ),
          dismissDirections: dismissDirections,
          slideOffFunc: () {
            if (onCancel != null) onCancel();
            cancelFunc();
          }
        ),
      groupKey: BotToast.notificationKey);
}

**Comment by MMMzq** [comment]
@LeiQiao 
如果你可以改代码的话,你可以直接套一个`ProxyDispose `在需要显示的Widget上面。
`ProxyDispose `的实现可以参考: [实现](https://github.com/MMMzq/bot_toast/blob/a4a590d3df66dd8e52ba3730c541dc7676d4a1cc/lib/src/toast_widget/toast_widget.dart#L33-L60)

这个功能今晚应该会加上的

**Comment by LeiQiao** [comment]
这样确实可以解决

**Comment by MMMzq** [comment]
@LeiQiao 
以添加`onClose`参数.更新版本即可

**Comment by LeiQiao** [comment]
awesome👍
