### ISSUE TITLE
Remove SafeArea from showCustomNotification

### ISSUE THREAD

**Issue by Paul-Todd** [MMMzq/bot_toast#37]
If you remove the SafeArea from showCustomNotification and let the custom widget handle it then it will allow you to have  the top notification color the status bar as well as the main control.

This is around line 225 for toast.dart

**Comment by MMMzq** [comment]
Using SafeArea can prevent the following situations from happening.

![说明](https://user-images.githubusercontent.com/28224568/76174141-67c8c180-61e0-11ea-986a-93eaea773683.gif)

**Comment by MMMzq** [comment]
If really needed, I can provide a `useSafeArea` parameter in` showCustomNotification`

**Comment by Paul-Todd** [comment]
That would work but then I could remove it from your control and put it back in mine.

In my use case I needed to have the safe area be a custom color (red in this case) we well as the notification, rather than having a green back status bar area and the rest as red.

**Comment by MMMzq** [comment]
I have a better suggestion: you can try using `showAnimationWidget` for more thorough customization.

see [showAnimationWidget](https://github.com/MMMzq/bot_toast/blob/02f363e60d8dbad2d6704c70d1d8033b99430c57/lib/src/toast.dart#L568)
