### ISSUE TITLE
Error: No named parameter with the name 'reverseDuration'.         reverseDuration: reverseDuration);

### ISSUE THREAD

**Issue by dafaWang** [MMMzq/bot_toast#38]
Compiler message:
file:///D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/bot_toast-2.3.0/lib/src/toast.dart:801:9: Error: No named parameter with the name 'reverseDuration'.
        reverseDuration: reverseDuration);
        ^^^^^^^^^^^^^^^
file:///D:/FlutterSDK/flutter/packages/flutter/lib/src/animation/animation_controller.dart:231:3: Context: Found this candidate, but the arguments don't match.
  AnimationController({
  ^
Compiler failed on G:\flutter_workspace\flutter_app\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

刚刚开始学习flutter,请问这个问题是什么原因?感谢

**Comment by MMMzq** [comment]
#18

**Comment by simon-das** [comment]
I encountered this error while using another package. Updating the flutter sdk solved my problem. It may also help someone else.
