### ISSUE TITLE
与FlutterBoost不兼容，并列多Navigator的形式可能失效

### ISSUE THREAD

**Issue by icespring** [MMMzq/bot_toast#41]
由于FlutterBoost混合栈方案是会创建多个平行的Navigator，当前的BotToast在寻找Navigator的时候，会找到最后一个Navigator并在此Navigator的Overlay中添加OverlayEntry，这就导致了当前显示的Navigator并不是需要添加toast的Navigator，显示也就不生效。

能不能使用findAncestorStateOfType向上寻找的方式，而非向下visitChildElements的方式寻找Navigator呢？

**Comment by MMMzq** [comment]
1. 关于`findAncestorStateOfType`和`visitChildElements`这两种方式我都用过,`findAncestorStateOfType`在1.x版本的时候就是使用此方法,但是会带来很多问题:
```dart
MaterialApp(
        title: 'BotToast Demo',
        navigatorObservers: [BotToastNavigatorObserver()],
        home: BotToastInit(
              child:EnterPage()
           ),
      )
```
假如home代表的Route被移除,则BotToastInit也将会被移除导致后续执行会有问题.因此相对于前者后者问题更少一点.

2.这个问题的原因不在于使用`findAncestorStateOfType`还是`visitChildElements`,而在于我不知道你是要我显示在哪一个`Navigator`上,因此我在写2.x版本的时候是以最后一个`BotToastInit`所在的`Navigator`为准的

**Comment by icespring** [comment]
那如果是这样的化，我希望可以像之前的版本一样，我可以在BotToastInit中传递GlobalKey来自行管理，这样可以为每个Navigator创建我自己的BotToastInit，也就避免了全局只有一个BotToastInit带来的尴尬。BotToastInit可以创建of方法方便下层找到对应Navigator的BotToastInit，不知道我的思路对不对?

**Comment by MMMzq** [comment]
1. `BotToast`目前是一个静态类
2. `BotToast`目前只能绑定一个`BotToastManager` 
3. `BotToastInit`可以创建出一个`BotToastManager`
```                                                      
BotToast ----使用------> BotToastManager  <--------提供----------BotToastInit
```
由于`BotToast`是静态类的原因,就算有多个`BotToastManager`可用,但是还是只能选择其中一个。

因此我目前想到的是:提供一个途径让`BotToast`动态绑定,而不是默认使用最后一个，又或者是直接将`BotToast`实例化

**Comment by icespring** [comment]
随着闲鱼的flutterboost的越来越多的应用，确实可能需要某种方式来解决并行Navigator应用的问题。

不依赖具体context确实是BotToast的巨大优势，或者可以考虑传递可选context的方式来动态绑定

**Comment by MMMzq** [comment]
@icespring 
这个我还要想一下怎么实现,可能不会那么快提供

**Comment by songjhh** [comment]
现在这个问题怎么样了，有办法先绕过去吗？

**Comment by MMMzq** [comment]
最近没什么时间,并且这个改动比较大,所以目前还没有计划.
不过现在是部分支持FlutterBoost的,

**Comment by songjhh** [comment]
谢谢你的回答！
请问一下，这个部分支持具体怎么接入呢？
我看readme写：
如果你项目有多个[Navigator],请将该BotToastNavigatorObserver添加到[Navigator.observers]
请问能给点代码片段，或者更加详细的描述吗？
刚入Flutter的门，暂时知识储备不能支撑解决这个问题，网上也搜索了很多但是还是没有解决，谢谢了！

MMMzq <notifications@github.com> 于2020年4月15日周三 下午10:51写道：

**Comment by MMMzq** [comment]
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorObservers: [BotToastNavigatorObserver()], ///添加BotToastNavigatorObserver
      home: Column(
        children: <Widget>[
          ///额外的Navigator 1
          Navigator(
              observers: [BotToastNavigatorObserver()], ///添加BotToastNavigatorObserver
              onGenerateRoute: (_) =>
                  MaterialPageRoute(builder: (_) => Scaffold())),
          
          ///额外的Navigator 2
          Navigator(
              observers: [BotToastNavigatorObserver()], ///添加BotToastNavigatorObserver
              onGenerateRoute: (_) =>
                  MaterialPageRoute(builder: (_) => Scaffold())),
        ],
      ),
    );
  }
}

```
因为BotToast的一些功能需要依赖`NavigatorObserver`,所有尽量在每一个`Navigator`都添加`BotToastNavigatorObserver`

**Comment by MMMzq** [comment]
@icespring 
我暂时提供一个临时的方法:
```dart
    TransitionBuilder transitionBuilder =
        FlutterBoost.init(postPush: _onRoutePushed);
    FlutterBoost.singleton.addBoostNavigatorObserver(BotToastNavigatorObserver());
    return MaterialApp(
        title: 'Flutter Boost example',
        navigatorObservers: [BotToastNavigatorObserver()],
        builder: (context, child) {
          child = transitionBuilder(context, child);
          return BotToastInit(
              child: Navigator(
                  onGenerateRoute: (_) => PageRouteBuilder(
                      opaque: false,
                      pageBuilder: (_, __, ___) => child),
                  observers: [BotToastNavigatorObserver()]));
        },
        home: Container());
```
- 我使用的是FlutterBoost的`v1.9.1-hotfixes`分支的Android example来进行测试的,目前BotToast已经可以使用了
- 不过`backButtonBehavior`参数会失效,原因是`flutter_boost`会影响`[WidgetsBindingObserver.didPopRoute]`的行为,请知悉

这几天我可能会把初始化的代码重新实现，以更好的适应这种情况

**Comment by songjhh** [comment]
> @icespring
> 我暂时提供一个临时的方法:
> 
> ```dart
>     TransitionBuilder transitionBuilder =
>         FlutterBoost.init(postPush: _onRoutePushed);
>     FlutterBoost.singleton.addBoostNavigatorObserver(BotToastNavigatorObserver());
>     return MaterialApp(
>         title: 'Flutter Boost example',
>         navigatorObservers: [BotToastNavigatorObserver()],
>         builder: (context, child) {
>           child = transitionBuilder(context, child);
>           return BotToastInit(
>               child: Navigator(
>                   onGenerateRoute: (_) => PageRouteBuilder(
>                       opaque: false,
>                       pageBuilder: (_, __, ___) => child),
>                   observers: [BotToastNavigatorObserver()]));
>         },
>         home: Container());
> ```
> 
> * 我使用的是FlutterBoost的`v1.9.1-hotfixes`分支的Android example来进行测试的,目前BotToast已经可以使用了
> 
> 这几天我可能会把初始化的代码重新实现，以更好的适应这种情况

感谢，亲测有效，暂时就这样先用

**Comment by MMMzq** [comment]
@songjhh 
更正一下:
`FlutterBoost.singleton.addBoostNavigatorObserver(BotToastNavigatorObserver());`这一行代码需要放到`MyApp`里的initState里运行

**Comment by songjhh** [comment]
> @songjhh
> 更正一下:
> `FlutterBoost.singleton.addBoostNavigatorObserver(BotToastNavigatorObserver());`这一行代码需要放到`MyApp`里的initState里运行

是的，恰好我一开始就放initState里了

**Comment by MMMzq** [comment]
你好可以升级到3.0版本进行适配
1.   在`initState`调用`    FlutterBoost.singleton.addBoostNavigatorObserver(BotToastNavigatorObserver());
`
2.
```dart
  @override
  Widget build(BuildContext context) {
    final boost = FlutterBoost.init(postPush: _onRoutePushed);
    final botFunc = BotToastInit();
    return MaterialApp(
        title: 'Flutter Boost example',
        builder: (context,child){
          child = boost(context,child);
          child = botFunc(context,child);
          return child;
        },
        home: Container());
  }
```

**Comment by DevinFu** [comment]
> 你好可以升级到3.0版本进行适配
> 
> 1. 在`initState`调用`   FlutterBoost.singleton.addBoostNavigatorObserver(BotToastNavigatorObserver());`
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     final boost = FlutterBoost.init(postPush: _onRoutePushed);
>     final botFunc = BotToastInit();
>     return MaterialApp(
>         title: 'Flutter Boost example',
>         builder: (context,child){
>           child = boost(context,child);
>           child = botFunc(context,child);
>           return child;
>         },
>         home: Container());
>   }
> ```

你好，按你的说法应当是升级到3.0版本后应该就能解决问题了。但是我升级到3.0版本，按照你提供的代码使用后发现`backButtonBehavior`参数依然无效。我使用的flutter_boost版本是task/task_v1.12.13_support_hotfixes，flutter版本是v1.12.13+hotfix.9. 是因为版本不匹配的问题吗？

**Comment by MMMzq** [comment]
这个是因为FlutterBoost的原因:flutter_boost会影响[WidgetsBindingObserver.didPopRoute]的行为,所以会导致`backButtonBehavior`参数失效

**Comment by DevinFu** [comment]
> 这个是因为FlutterBoost的原因:flutter_boost会影响`WidgetsBindingObserver.didPopRoute`的行为,所以会导致`backButtonBehavior`参数失效
> 
> 我上面的回复也说明了这种的情况,你可以往上翻一下评论

哦哦， 好的， 我之前就看过上面评论了。 误解你的意思了，我以为你的意思是升级到3.0后这个问题解决了。 感谢你提供的这个package，功能很棒，实现方式也很棒，谢谢。
