### ISSUE TITLE
如何在 loading 显示时拦截返回键？

### ISSUE THREAD

**Issue by hidetag** [MMMzq/bot_toast#45]
我看 demo 中有个例子是自定义 Widget，但那是个 AlertDialog，在构建 Widget 时用 WillPopScope 去处理，这样没问题，但实际上这种方式本质是 push 了 Widget 到路由中
能否开放一个能力，让调用方能控制物理返回键的作用

**Comment by MMMzq** [comment]
确实有别的方式实现同样的功能，这个功能确实可以提供

**Comment by hidetag** [comment]
采用 WillPopScope 或者直接从 Android 原生进行控制也不是不行，只是对现有项目改动相对较多；Toast 之前使用 OKToast，对话框采用 Flutter 原生，但原生对话框如果在界面上同时有两个对话框，对话框的关闭逻辑就乱了，所以下定决心全部改为 overlay 实现 /哭

**Comment by MMMzq** [comment]
我想着添加一个`BackButtonBehavior`参数,用来指示物理返回按钮的行为
其`BackButtonBehavior`有三个值
1. `BackButtonBehavior.none`  不做处理
2. `BackButtonBehavior.ignoer` 忽视此次点击返回事件
3. `BackButtonBehavior.close` 关闭Toast,并且事件不再传递给下一个处理者(通常就是`Navigator`)

假设同时有`A`,`B`两个模态框,先显示`A`再显示`B`,都设置为`BackButtonBehavior.close`,第一次点击则关闭`B`,第二次点击则关闭`A`,第三次则不再拦截后退事件,让`Navigator`接管事件，通常就是表现就是页面后退

**Comment by hidetag** [comment]
很棒的想法，应该能覆盖所有需求了

**Comment by MMMzq** [comment]
`2.4.0`以提供此功能

**Comment by hidetag** [comment]
多谢，我更新版本看看 /色

**Comment by hidetag** [comment]
已测试，可用，多谢
