### ISSUE TITLE
创建方式这样是否会更好呢？

### ISSUE THREAD

**Issue by HongxiangShe** [MMMzq/bot_toast#47]
```
MaterialApp(
  builder: (context, child) {
    return BotToastInit(child: child);
  },
  navigatorObservers: [BotToastNavigatorObserver()],
  theme: ThemeData(
    primarySwatch: Colors.blue,
  ),
  home: MyHomePage(),
);

**Comment by MMMzq** [comment]
我认为有好的有坏的地方:
好处就是`visitChildElements`方法效率更高。

不好的地方可能是更容易触发`BotToastInit`重新`build`。重新`rebuild`意味着需要重新调用`visitChildElements`

**Comment by HongxiangShe** [comment]
> 我认为有好的有坏的地方:
> 好处就是`visitChildElements`方法效率更高。
> 
> 不好的地方可能是更容易触发`BotToastInit`重新`build`。重新`rebuild`意味着需要重新调用`visitChildElements`
> 
> 不过这种影响都是微乎其微的

其实这种方式BotToastInit被重新build的概率还是比较低的，除非当你修改了一些不常见的东西。

**Comment by MMMzq** [comment]
这种使用方式比原先的使用方法有什么突出的好处?

**Comment by HongxiangShe** [comment]
嗯嗯， 的确不会有特别大的性能提升

**Comment by MMMzq** [comment]
如果没有别的问题我先关闭了,有问题可重新打开

**Comment by MMMzq** [comment]
@HongxiangShe 
我发现确实使用`builder`更好,可以不依赖`Navigator`

**Comment by HongxiangShe** [comment]
是这样，但还是建议builder: BotToastInit() 初始化，这样似乎封装的太过了；

**Comment by MMMzq** [comment]
可以参考下面的方式进行处理
```dart
final transitionBuilder = BotToastInit();
MaterialApp(
        ....
        navigatorObservers: [BotToastNavigatorObserver()],
        builder: (context, child) {
          //do something

          child = transitionBuilder(context, child);
          return child;
        })
```

**Comment by HongxiangShe** [comment]
嗯嗯，ok
