### ISSUE TITLE
Doesn't seem to be working with Overlay

### ISSUE THREAD

**Issue by b-cancel** [MMMzq/bot_toast#48]
It doesn't seem to be working with overlay... I used overlay so I can calculate the size of my hamburger menu items... then based on that I can open the menu by shifting the entire app a little to one side... 

but now the toast won't come up

**Comment by MMMzq** [comment]
I don't quite understand what you mean, can you provide a case that can reproduce this error?

**Comment by b-cancel** [comment]
@MMMzq well you toolkit uses overlay to make the toasts
when I use overlay the toasts wont work

I was using overlay to first build a side menu, then grab its size
and then use that value to shift my entire app to the left so the menu could show up on the right
I had to use an alternative solution that didn't use overlay to get toasts to work

I noticed the problem here
https://github.com/b-cancel/b-cancel.github.io/tree/dd669dea5ae5f1e9eaca2bd712dfcda9bec535e4
its my personal portfolio website
go into the portfolio file and run that on flutter and see the problem

**Comment by b-cancel** [comment]
@MMMzq truth be told it might be way too much work to fix
but at least you can notice the limitation
or on the off chance I just wasn't using it right, you might be able to instruct others on how to use it properly with overlay

**Comment by MMMzq** [comment]
I tried to run, but the build failed, it seems to be related to flutter web
