### ISSUE TITLE
如何手动关闭Loading

### ISSUE THREAD

**Issue by xxzj990** [MMMzq/bot_toast#5]
BotToast.showLoading调用后如何手动关闭？

**Comment by xxzj990** [comment]
如果手动调用：BotToast.closeAllLoading()，会报下面错误

> E/flutter (12773): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 671 pos 7: '_ticker != null': AnimationController.animateWith() called after AnimationController.dispose()
> E/flutter (12773): AnimationController methods should not be used after calling dispose.
> E/flutter (12773): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
> E/flutter (12773): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (12773): #2      AnimationController.animateWith (package:flutter/src/animation/animation_controller.dart:671:7)
> E/flutter (12773): #3      AnimationController.repeat (package:flutter/src/animation/animation_controller.dart:626:12)
> E/flutter (12773): #4      BallSpinFadeLoaderIndicator.startAnims.<anonymous closure> (package:loading/indicator/ball_spin_fade_loader_indicator.dart:49:24)
> E/flutter (12773): #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
> E/flutter (12773): #6      _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (12773): #7      _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (12773): #8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (12773): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (12773): #10     _rootRun (dart:async/zone.dart:1124:13)
> E/flutter (12773): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (12773): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> E/flutter (12773): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
> E/flutter (12773): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> E/flutter (12773): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> E/flutter (12773): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> E/flutter (12773): 
> I/chatty  (12773): uid=10287(com.szhq.tbox) 1.ui identical 4 lines
> E/flutter (12773): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 671 pos 7: '_ticker != null': AnimationController.animateWith() called after AnimationController.dispose()
> E/flutter (12773): AnimationController methods should not be used after calling dispose.
> E/flutter (12773): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
> E/flutter (12773): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (12773): #2      AnimationController.animateWith (package:flutter/src/animation/animation_controller.dart:671:7)
> E/flutter (12773): #3      AnimationController.repeat (package:flutter/src/animation/animation_controller.dart:626:12)
> E/flutter (12773): #4      BallSpinFadeLoaderIndicator.startAnims.<anonymous closure> (package:loading/indicator/ball_spin_fade_loader_indicator.dart:49:24)
> E/flutter (12773): #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
> E/flutter (12773): #6      _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (12773): #7      _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (12773): #8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (12773): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (12773): #10     _rootRun (dart:async/zone.dart:1124:13)
> E/flutter (12773): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (12773): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> E/flutter (12773): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
> E/flutter (12773): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
> E/flutter (12773): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
> E/flutter (12773): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by xxzj990** [comment]
调用toastBuilder: (cancelFunc) {}的回调函数可以好像。

**Comment by MMMzq** [comment]
@xxzj990  使用Loading建议把crossPage设置为true,这样在用户按物理的返回键时能自动关闭

**Comment by MMMzq** [comment]
@xxzj990  每个BotToast.showXxx都会返回一个关闭函数,调用即可提前关闭对应的Toast
