### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by cv0cv0** [MMMzq/bot_toast#50]
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 132 pos 12: '_overlay != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      OverlayEntry.remove 
package:flutter/…/widgets/overlay.dart:132
#3      BotToastManager.remove.<anonymous closure> 
package:bot_toast/src/bot_toast_manager.dart:130
#4      safeRun.<anonymous closure> 
package:bot_toast/src/bot_toast_manager.dart:11
#5      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1102
#6      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1049
...
════════════════════════════════════════════════════════════════════════════════

**Comment by MMMzq** [comment]
@cv0cv0 你的`bot_toast`版本是多少？

**Comment by cv0cv0** [comment]
@MMMzq 用的最新的，2.4.0 。

**Comment by cv0cv0** [comment]
@MMMzq Flutter 版本是：1.12.13+hotfix.9
项目中还使用了 oktoast。

**Comment by MMMzq** [comment]
@cv0cv0 
能否提供一个可以重现的demo?
这样看不出来问题

**Comment by cv0cv0** [comment]
@MMMzq https://github.com/cv0cv0/bot_toast_demo

**Comment by cv0cv0** [comment]
@MMMzq 发现问题了，是我没初始化完全。

**Comment by cv0cv0** [comment]
@MMMzq 可以了，不好意思，耽误你时间了。
