### ISSUE TITLE
在 showNotification 中调用 onTap 不会导致 Notification 消失

### ISSUE THREAD

**Issue by cv0cv0** [MMMzq/bot_toast#51]
别的控件都会传入一个 CancelFunc 用于取消显示，onTap 没有。

**Comment by MMMzq** [comment]
```dart
    CancelFunc cancelFunc;
    cancelFunc=BotToast.showNotification(onTap: (){
      //do something
      cancelFunc();  //关闭显示Toast
    });
```

**Comment by cv0cv0** [comment]
> ```dart
>     CancelFunc cancelFunc;
>     cancelFunc=BotToast.showNotification(onTap: (){
>       //do something
>       cancelFunc();  //关闭Toast
>     });
> ```

想到了这样的方式，但是感觉这样子不太优雅。

**Comment by MMMzq** [comment]
@cv0cv0 
还有一种方式,使用`showCustomNotification`自行传入`toastBuilder`参数
