### ISSUE TITLE
How change notification color

### ISSUE THREAD

**Issue by Jan-pp** [MMMzq/bot_toast#54]
showNotification() for example shows a white notification. Is there a way to change the background color of the notification (without having to make a completely custom one)? The rest of my app is pretty white too so it doesn't stand out enough.

Also it would be nice if I could set the margin (the space between the notification and the edges of te screen).

Nice plugin BTW.

**Comment by MMMzq** [comment]
You can use the `showCustomNotification` method

Example:
```dart
  BotToast.showCustomNotification(
      toastBuilder: (cancel) {
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: Card(
            color: Colors.grey,
            child: ListTile(
              title: const Text('title'),
            ),
          ),
        );
      });
```
