### ISSUE TITLE
Initializing BotToastInit

### ISSUE THREAD

**Issue by ahmadf20** [MMMzq/bot_toast#55]
Hi, I'm sorry for opening this nonsense issue due to my lack of awareness. I think it's more like a question than a bug. I've tried to find the solution myself but I couldn't make it and I don't know where else to ask.

I just updated the package to the latest version which has a new way of initializing the package. In the previous version, we have to wrap our MaterialApp widget with BotToastInit which is fine for me. But, in the latest version, we need to put the BotToastInit inside the builder in the MaterialApp widget. However, I can't do that because I already have another function to put inside the builder which I used to remove the scroll bound glow effect for my whole app.

This is my code using the previous version of the package:

```

child: BotToastInit(
        child: MaterialApp(
          title: 'MyApp',
          navigatorObservers: [BotToastNavigatorObserver()],
          builder: (context, child) {
            return ScrollConfiguration(
              behavior: MyBehavior(), // remove scroll bound glow effect
              child: child,
            );
          },
          home: HomeScreen(),
        ),
      ),

```

Is there any way to call the botToastInit without having to replace my function with botToastInit inside the builder?

Thanks in advance!

**Comment by MMMzq** [comment]
Example:
```dart
  Widget build(BuildContext context) {
    final botToastBuilder = BotToastInit();
    return MaterialApp(
      builder: (context, child) {
        child = ScrollConfiguration(
          behavior: MyBehavior(),
          child: child,
        );

        child = botToastBuilder(context,child);
        return child;
      },
      title: 'BotToast Demo',
      navigatorObservers: [BotToastNavigatorObserver()],
      home: HomeScreen(),
    );
  }
```

**Comment by ahmadf20** [comment]
I can't believe it! Your example code above works like a charm. Thanks for taking the time to answer my question.
