### ISSUE TITLE
showLoading能不能提供一个参数 用于自定义指示器

### ISSUE THREAD

**Issue by qcdys** [MMMzq/bot_toast#57]
比如
`
BotToast.showLoading(
     child: const SpinKitRipple(color: Colors.white)
);
`

这里我使用的是flutter_spinkit插件 
这对于新手来说是非常便捷的

**Comment by MMMzq** [comment]
你可以尝试使用`BotToast.showCustomLoading`方法

**Comment by qcdys** [comment]
> 你可以尝试使用`BotToast.showCustomLoading`方法
> 使用方式可以参考`example`的`showCustomLoading`例子
> 或者更简单的是直接使用`showCustomLoading`的`toastBuilder`参数即可

我提这个建议是因为默认的loading太android风  所以我觉得很多人都会想改这个样式   showCustomLoading可以用确实没错 可是对于初学者来说 很可能一个样式就拒之门外 
哈哈哈 可改可不改 我关闭了 谢谢大佬

**Comment by MMMzq** [comment]
`showCustomLoading`和`showLoading`的差别就是`toastBuilder`参数.其他都是一样的一个有默认参数一个没有
