### ISSUE TITLE
[Question] Notification background color and location

### ISSUE THREAD

**Issue by rgb1380** [MMMzq/bot_toast#59]
Great work. This is a simple to use and very versatile toast plug-in. I have two questions:
1. Is it possible to display the notification at the bottom of the page?
2. Is it possible to change the background color of a notification?

**Comment by MMMzq** [comment]
You can use `showCustomNotification` method

Example:
```dart
showCustomNotification(
        align: const Alignment(0, 0.99),  //1.Control position
       ....
        toastBuilder: (cancel) {
          return Card(
            color: Colors.lightBlue,  //2. Custom Color
            child: ListTile(
                ......
          );
        });
```

**Comment by rgb1380** [comment]
Thanks for the quick response.
