### ISSUE TITLE
BotToast crash on reload

### ISSUE THREAD

**Issue by alonhh** [MMMzq/bot_toast#60]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown building Builder(dirty):
Expected a value of type 'Widget', but got one of type '_Future<dynamic>'

The relevant error-causing widget was:
  Stack
  file:///usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-3.0.0/lib/src/bot_toast_manager.dart:74:12

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 64:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 444:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 391:9        as
packages/flutter/src/material/page.dart 82:34                                     buildPage
packages/flutter/src/widgets/routes.dart 804:43                                   <fn>
packages/flutter/src/widgets/basic.dart 7006:48                                   build
packages/flutter/src/widgets/framework.dart 4580:28                               build
packages/flutter/src/widgets/framework.dart 4506:15                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 5951:32                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5834:14                               mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4485:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                mount
packages/flutter/src/widgets/framework.dart 3450:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                               updateChild
packages/flutter/src/widgets/framework.dart 5584:32                               updateChildren
packages/flutter/src/widgets/framework.dart 5961:17                               update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4711:5                                update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4866:5                                update
packages/flutter/src/widgets/inherited_notifier.dart 181:11                       update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 5841:14                               update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4711:5                                update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 5841:14                               update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 5841:14                               update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 4587:5                                update
packages/flutter/src/widgets/framework.dart 3205:14                               updateChild
packages/flutter/src/widgets/framework.dart 4531:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4679:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                rebuild
packages/flutter/src/widgets/framework.dart 2627:31                               buildScope
packages/flutter/src/widgets/binding.dart 864:49                                  drawFrame
packages/flutter/src/rendering/binding.dart 284:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1074:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1013:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 929:5                                 [_handleDrawFrame]
lib/_engine/engine/window.dart 578:13                                             _invoke
lib/_engine/engine/window.dart 222:5                                              invokeOnDrawFrame
lib/_engine/engine.dart 213:18                                                    <fn>

**Comment by MMMzq** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**
Add any other context about the problem here.

**Comment by alonhh** [comment]
Describe the bug:

When opening Flutter WEB website.com#/home/ the following error occurs:
The following TypeErrorImpl was thrown building Builder(dirty):
Expected a value of type 'Widget', but got one of type '_Future<dynamic>'
file://flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-3.0.0/lib/src/bot_toast_manager.dart:74:12

To Reproduce
When opening Flutter WEB website.com#/home the following error occurs:
The following TypeErrorImpl was thrown building Builder(dirty):
Expected a value of type 'Widget', but got one of type '_Future<dynamic>'


Version (please complete the following information):

Flutter Version: 1.17.1
OS: WEB
BotToast Version : 3.0.0

**Comment by MMMzq** [comment]
I ran the example and everything works

This may be a bug in Flutter Web, you can try to upgrade Flutter.
