### ISSUE TITLE
Couldn't configure the Bot Toast

### ISSUE THREAD

**Issue by zahedul** [MMMzq/bot_toast#65]
**In main.dart file**
```
MaterialApp(
    title: 'My App',
    builder: BotToastInit(),
    navigatorObservers: [BotToastNavigatorObserver()],
    theme: ThemeData(
      ...
    ),
    onGenerateRoute: ...,
    initialRoute: homeRoute,
  )
```

**Calling from another widget (different file)**
```
BotToast.showText(text:"Hello world");
```

**Error In console**
```
I/flutter (26389): hello
E/flutter (26389): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (26389): Receiver: null
E/flutter (26389): Tried calling: call()
E/flutter (26389): #0      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:719:17)
E/flutter (26389): <asynchronous suspension>
E/flutter (26389): #1      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart)
E/flutter (26389): #2      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:729:15)
E/flutter (26389): #3      List.forEach (dart:core-patch/growable_array.dart:282:8)
E/flutter (26389): #4      BotToast.showEnhancedWidget (package:bot_toast/src/toast.dart:728:13)
E/flutter (26389): #5      BotToast.showAnimationWidget (package:bot_toast/src/toast.dart:611:12)
E/flutter (26389): #6      BotToast.showCustomText (package:bot_toast/src/toast.dart:331:12)
E/flutter (26389): #7      BotToast.showText (package:bot_toast/src/toast.dart:277:12)
E/flutter (26389): #8      _ShopScreenState.tapAction (package:beasy/modules/home/screens/shop.screen.dart:26:14)
E/flutter (26389): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (26389): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (26389): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (26389): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (26389): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (26389): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (26389): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (26389): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (26389): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (26389): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (26389): #19     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (26389): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (26389): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (26389): #22     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (26389): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (26389): 

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:bot_toast/src/bot_toast_init.dart': Failed assertion: line 10 pos 10: '_key?.currentState != null': is not true.

When the exception was thrown, this was the stack: 
#2      botToastManager (package:bot_toast/src/bot_toast_init.dart:10:10)
#3      BotToast.showWidget (package:bot_toast/src/toast.dart:829:5)
#4      BotToast.showEnhancedWidget (package:bot_toast/src/toast.dart:767:18)
#5      BotToast.showAnimationWidget (package:bot_toast/src/toast.dart:611:12)
#6      BotToast.showCustomText (package:bot_toast/src/toast.dart:331:12)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#c7a5d
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(72.9, 304.3)
  finalLocalPosition: Offset(72.9, 48.3)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Version (please complete the following information):**
 - Flutter Version: v1.17.1
 - OS: Android
 - BotToast Version : 3.0.0

**Comment by MMMzq** [comment]
I can't reproduce this error, can you provide an error example? :}

**Comment by saranyalekshmanan** [comment]
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
I got above mentioned error with this error message 


The following assertion was thrown while handling a gesture:
'package:bot_toast/src/bot_toast_init.dart': Failed assertion: line 10 pos 10: '_botToastInitKey?.currentState?._botToastManager != null': is not true.

When the exception was thrown, this was the stack: 
#2      botToastManager (package:bot_toast/src/bot_toast_init.dart:10:10)
#3      BotToast.showWidget (package:bot_toast/src/toast.dart:827:5)
#4      BotToast.showEnhancedWidget (package:bot_toast/src/toast.dart:765:18)
#5      BotToast.showAnimationWidget (package:bot_toast/src/toast.dart:611:12)
#6      BotToast.showCustomNotification (package:bot_toast/src/toast.dart:209:12)
...
Handler: "onTap"

**Comment by dromedian** [comment]
we are experiencing the same issues, there's not much to add honestly

**Comment by MMMzq** [comment]
If you want to solve the problem as soon as possible, you can provide me with an example that reproduces this problem

**Comment by DTharaka** [comment]
Is there a solution for this issue?

**Comment by KasunHasanga** [comment]
```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'YourAppTitle',
      builder: BotToastInit(),
      navigatorObservers: [BotToastNavigatorObserver()],
      home: YourWidget(),
    );
  }
```

Try this

**Comment by Ingrame** [comment]
I just solved this problem. You need to pass the child context through the builder and input it to the child=botToastBuilder (context, child) for example
`return ScreenUtilInit(
      designSize: AppConfig.screenSize, //设计稿中的设备尺寸
      minTextAdapt: true,  //是否根据宽度/高度中的最小值适配文字
      splitScreenMode: true, //支持分屏尺寸
      builder: (context, child){
       return GetMaterialApp(
          title: 'wallet',
          initialRoute: initialRoute,
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            primarySwatch: Colors.blue,
            platform: TargetPlatform.iOS,
          ),
          getPages: generateRoute(),
           navigatorObservers: [BotToastNavigatorObserver()],
           builder: (context, child) {
             child = botToastBuilder(context,child);
             return MediaQuery(
             //设置文字大小不随系统设置改变
             data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
             child: child!,
           );
         },
       );
      },
    );`

**Comment by Ingrame** [comment]
I just solved this problem. You need to pass the child context through the builder and input it to the child=botToastBuilder (context, child) for example
`
return ScreenUtilInit(
      designSize: AppConfig.screenSize, //设计稿中的设备尺寸
      minTextAdapt: true,  //是否根据宽度/高度中的最小值适配文字
      splitScreenMode: true, //支持分屏尺寸
      builder: (context, child){
       return GetMaterialApp(
          title: 'wallet',
          initialRoute: initialRoute,
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            primarySwatch: Colors.blue,
            platform: TargetPlatform.iOS,
          ),
          getPages: generateRoute(),
           navigatorObservers: [BotToastNavigatorObserver()],
           builder: (context, child) {
             child = botToastBuilder(context,child);
             return MediaQuery(
             //设置文字大小不随系统设置改变
             data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
             child: child!,
           );
         },
       );
      },
    );
`

**Comment by Ingrame** [comment]
> 

sorry, I didn't format the code
