### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by Zengyonghao** [MMMzq/bot_toast#66]
始终找不到问题原因

   MaterialApp(
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          S.delegate
        ],
        builder:  BotToastInit(),
        supportedLocales: S.delegate.supportedLocales,
        onGenerateTitle: (context) => S.of(context).app_name,
        navigatorObservers: [BotToastNavigatorObserver()],
        theme: _theme,
        //home: LoginPage()
        home: home,
      )`

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'addObserver' was called on null.
E/flutter ( 7295): Receiver: null
E/flutter ( 7295): Tried calling: addObserver(Instance of 'BotToastWidgetsBindingObserver')
E/flutter ( 7295): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 7295): #1      new BotToastWidgetsBindingObserver._ (package:bot_toast/src/bot_toast_init.dart:18:29)
E/flutter ( 7295): #2      BotToastWidgetsBindingObserver._singleton (package:bot_toast/src/bot_toast_init.dart:24:8)
E/flutter ( 7295): #3      BotToastWidgetsBindingObserver._singleton (package:bot_toast/src/bot_toast_init.dart:23:47)
E/flutter ( 7295): #4      BotToastInit (package:bot_toast/src/bot_toast_init.dart:53:34)
E/flutter ( 7295): #5      Application.build (package:protonlink/router/app.dart:65:19)
E/flutter ( 7295): #6      main (package:protonlink/main.dart:8:27)`

**Comment by Zengyonghao** [comment]
我的错 初始化需要context

**Comment by DuMengjie** [comment]
@Zengyonghao 同样的问题，请问是怎么解决的？

**Comment by sathishmscict** [comment]
Am also faced same issue : 

Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
D/FlutterActivityAndFragmentDelegate(17330): Executing Dart entrypoint: main, and sending initial route: /
Debug service listening on ws://127.0.0.1:58249/QfKCQPE11AA=/ws
Syncing files to device Nokia 6 1 Plus...
W/Gralloc3(17330): mapper 3.x is not supported
E/flutter (17330): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'addObserver' was called on null.
E/flutter (17330): Receiver: null
E/flutter (17330): Tried calling: addObserver(Instance of 'BotToastWidgetsBindingObserver')
E/flutter (17330): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (17330): #1      new BotToastWidgetsBindingObserver._ (package:bot_toast/src/bot_toast_init.dart:18:29)
E/flutter (17330): #2      BotToastWidgetsBindingObserver._singleton (package:bot_toast/src/bot_toast_init.dart:24:8)
E/flutter (17330): #3      BotToastWidgetsBindingObserver._singleton (package:bot_toast/src/bot_toast_init.dart:23:47)
E/flutter (17330): #4      BotToastInit (package:bot_toast/src/bot_toast_init.dart:53:34)
E/flutter (17330): #5      main (package:flutterchatbot/main.dart:10:14)
E/flutter (17330): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (17330): #7      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (17330): #8      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (17330): #9      _runZoned (dart:async/zone.dart:1518:10)
E/flutter (17330): #10     runZoned (dart:async/zone.dart:1502:12)
E/flutter (17330): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (17330): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (17330): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (17330):

**Comment by sathishmscict** [comment]
> My wrong initialization requires context

Could you please share what you did?

**Comment by sathishmscict** [comment]
> @Zengyonghao The same problem, how is it solved?

Hi @Zengyonghao, i am found solution.



void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
  
    return MaterialApp(
      builder: BotToastInit(),
      navigatorObservers: [BotToastNavigatorObserver()],
      title: 'Chat-bot',
      home: HomeScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}



Only the change is  => 

  builder: BotToastInit(),
  navigatorObservers: [BotToastNavigatorObserver()],

Above properties required context , so need to add inside a widget and add it into main method. Earlier am adding these properties inside a main method am faced issue. Once i moved inside a widget issue resolved. Hope it will help you.
