### ISSUE TITLE
English language for documentation.

### ISSUE THREAD

**Issue by nateshmbhat** [MMMzq/bot_toast#67]
Please add documentation in English Language.

**Comment by MMMzq** [comment]
1. My English level is not particularly good and I cannot provide English documentation for the time being.

**Comment by fehernyul** [comment]
> My English level is not very good, so I can't provide English documentation for the time being.

If you can write this sentence, the documentation will be very good! (more good than now) :)

**Comment by MadeBugs** [comment]
> My English level is not very good, so I can't provide English documentation for the time being.

your english is very good, I can understand you

**Comment by zhoulijun12315** [comment]
> My English level is not very good, so I can't provide English documentation for the time being.

your english is very good, I can understand you too.

**Comment by yubaokang** [comment]
your english is very good, I can understand you too too.

**Comment by hellobq** [comment]
your english is very good, I can understand you too too.
me too...

**Comment by MMMzq** [comment]
If I have time, I will try to translate it into English.   ：）

**Comment by aytunch** [comment]
On top of English, I think readme needs to be updated with all of the field's explanations.
We don't have them in documentation as well.
For instance I don't understand what `wrapAnimation` and `wrapToastAnimation` are how they should be used.

**Comment by MMMzq** [comment]
English documentation has been added.
