### ISSUE TITLE
Add message option for BotToast.showLoading()

### ISSUE THREAD

**Issue by chitgoks** [MMMzq/bot_toast#69]
Instead of just the loading icon

**Comment by MMMzq** [comment]
1.  Can you explain in more detail what options need to be added?

2. Maybe you can try using the `showCustomLoading` method.

**Comment by chitgoks** [comment]
ah i didnt know about the showCustomLoading. its not kn the readme.

thanks

**Comment by chitgoks** [comment]
ah yes. i saw it. My feature request was more simplifying it to the user that they provide a string message rather than having to create and pass widgets to it. but it works nonetheless.

if you do not have plans to accept this feature request, you can close it. thank you

**Comment by MMMzq** [comment]
There are currently no plans to add this feature, but I will improve the readme, thank you for your feedback. :}

**Comment by chitgoks** [comment]
yes please provide a sample in the readme :D in my use case i only want to include a text below the loading .. e..g like below

    O
Loading ...

**Comment by chitgoks** [comment]
I looked at the source code. unless im mistaken, your sample code for creating a custom loading has so many code in it.
so i hope you can provide a simpler showCustomLoading(text: 'Loading') by providing a String message option as parameter instead of the toastBuilder having to re-create everything just to add another widget and recreating the animation code.

**Comment by MMMzq** [comment]
```dart
//1 
class TextLoading extends StatelessWidget {
  final String text;

  const TextLoading({Key key, this.text}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(15),
      decoration: const BoxDecoration(
          color: Colors.black54,
          borderRadius: BorderRadius.all(Radius.circular(8))),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          const CircularProgressIndicator(
            backgroundColor: Colors.white,
          ),
          Padding(
            padding: const EdgeInsets.only(top: 8.0),
            child: Text(
              text,
              style: const TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }
}

//2 
BotToast.showCustomLoading(toastBuilder: (_)=>const TextLoading(text: 'Loading ... '));
```

**Comment by chitgoks** [comment]
Thank you . i will use this temporary workaround. I still hope you will reconsider. it will make it much simpler for users.
