### ISSUE TITLE
TextField 

### ISSUE THREAD

**Issue by taozhipeng1990** [MMMzq/bot_toast#71]
showEnhancedWidget 一个自定的Widget
如果存在TextField 会报错

**Comment by MMMzq** [comment]
-  这个问题是`TextField自身的依赖问题`
- 如果`TextField`的`decoration`字段不为空,则要要求其祖先之必须是`Material`,而`Scaffold`和`Material`都可以提供此依赖(注意`TextField`,`Material`,`Scaffold`本身都会吸收点击事件,从而导致`bot_toast`的一些功能失效,如:`clickClose`,`allowClick`)
- 二是要求`Overlay`也要作为其祖先之一,`TextField`将会使用`Overlay`来显示工具栏

##### 一个可用的例子:
```dart
                  BotToast.showEnhancedWidget(
                      crossPage: false,
                      toastBuilder: (_) => Material(
                        child: Overlay(
                          initialEntries: [
                            OverlayEntry(builder: (_) => Center(child: TextField()))
                          ],
                        ),
                      ));
```

##### 如果需要显示`TextField`,建议使用推路由的方式更合适.

**Comment by taozhipeng1990** [comment]
好的 谢谢大佬。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MMMzq"<notifications@github.com&gt;; 
发送时间: 2020年7月14日(星期二) 上午9:38
收件人: "MMMzq/bot_toast"<bot_toast@noreply.github.com&gt;; 
抄送: "让一切随风"<414111907@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MMMzq/bot_toast] TextField  (#71)





  
这个问题是TextField自身的依赖问题
 
如果TextField的decoration字段不为空,则要要求其祖先之必须是Material,而Scaffold和Material都可以提供此依赖(注意TextField,Material,Scaffold本身都会吸收点击事件,从而导致bot_toast的一些功能失效,如:clickClose,allowClick)
 
二是要求Overlay也要作为其祖先之一,TextField将会使用Overlay来显示工具栏
  
一个可用的例子:
                   BotToast.showEnhancedWidget(                       crossPage: false,                       toastBuilder: (_) =&gt; Material(                         child: Overlay(                           initialEntries: [                             OverlayEntry(builder: (_) =&gt; Center(child: TextField()))                           ],                         ),                       ));
 
如果需要显示TextField,建议使用推路由的方式更合适.
