### ISSUE TITLE
Background color is full screen by default?

### ISSUE THREAD

**Issue by awarmfastbear** [MMMzq/bot_toast#74]
**Describe the bug**
When trying to use the showCustomText toast notification I'm just trying to make a small toast notification with text and a color background. Instead I am getting a full screen color with my text. How do I prevent this?

**To Reproduce**

Add BotToast to the App, apply this code on a trigger:

```
        BotToast.showCustomText(
            toastBuilder: (_) {
              return Text("Hello?");
            },
            backgroundColor: Colors.amberAccent);
      }
```

**Expected behavior**
The background color by default should not take up the full screen in my opinion. It should be the same size as the text with some padding.

**Screenshots**

<img src="https://user-images.githubusercontent.com/25071166/90318424-3d90d380-dee5-11ea-86e2-3b0a14f8d80e.png" width="250" >

**Version (please complete the following information):**
 - Flutter Version: 1.20.2
 - OS: Android
 - BotToast Version : ^3.0.1

**Comment by MMMzq** [comment]
```dart
  BotToast.showCustomText(toastBuilder: (_) {
    return Container(
      padding: EdgeInsets.all(8),
      child: Text("Hello?"),
      color: Colors.amberAccent,
    );
  });
```
