### ISSUE TITLE
Toast里面放输入框 呼出键盘之后位置错误

### ISSUE THREAD

**Issue by itMcdull** [MMMzq/bot_toast#75]
我用的BotToast.showAnimationWidget()， toastBuilder返回了一个AlertDialog。dialog的content放了一个TextField是不支持这样使用吗，

**Comment by MMMzq** [comment]
请参考 #71

**Comment by itMcdull** [comment]
> 请参考[＃71](https://github.com/MMMzq/bot_toast/issues/71)

 因为设计原因，我不能使用推路由的方式，我需要在当前页面输入我的内容， 有具体方法吗，

**Comment by itMcdull** [comment]
![image](https://user-images.githubusercontent.com/40596015/90390352-c2cee080-e0bd-11ea-82ae-967b832749c0.png)
我可能说的误解了您，我在dialog中放了一个textfield，然后点击输入框的时候，键盘弹起，导致我的dailog就飞我顶部了

**Comment by MMMzq** [comment]
@itMcdull 
我会提供一个`enableKeyboardSafeArea`参数放禁止KeyboardSafeArea

**Comment by MMMzq** [comment]
升级到`v3.0.3`来使用此参数

**Comment by itMcdull** [comment]
问题得到了解决，非常感谢

**Comment by itMcdull** [comment]
另一个问题 
![image](https://user-images.githubusercontent.com/40596015/96113061-29ce1180-0f16-11eb-827e-cc7a4770f798.png)
`
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No Overlay widget exists above EditableText-[LabeledGlobalKey<EditableTextState>#ceaf1](controller: TextEditingController#2825a(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))), focusNode: FocusNode#213a9, debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1), inherit: false, color: Color(0xdd000000), family: .SF UI Text, size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, textAlign: start, keyboardType: TextInputType(name: TextInputType.text, signed: null, decimal: null), dirty, dependencies: [Directionality, _FocusMarker, MediaQuery], state: EditableTextState#8e272(tickers: tracking 2 tickers)).
Usually the Navigator created by WidgetsApp provides the overlay. Perhaps your app content was created above the Navigator with the WidgetsApp builder parameter.
'package:flutter/src/widgets/text_selection.dart':
Failed assertion: line 304 pos 12: 'overlay != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      new TextSelectionOverlay 
package:flutter/…/widgets/text_selection.dart:304
#3      EditableTextState._handleSelectionChanged 
package:flutter/…/widgets/editable_text.dart:2016
#4      RenderEditable._handleSelectionChange 
package:flutter/…/rendering/editable.dart:470
#5      RenderEditable.selectWordEdge 
package:flutter/…/rendering/editable.dart:1868
#6      _TextFieldSelectionGestureDetectorBuilder.onSingleTapUp 
package:flutter/…/material/text_field.dart:107
...
Handler: "onTapUp"
Recognizer: _TransparentTapGestureRecognizer#b9669
    debugOwner: _TextSelectionGestureDetectorState#5b9a3
    state: ready
    won arena
    finalPosition: Offset(220.0, 397.7)
    finalLocalPosition: Offset(148.5, 17.7)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
`

**Comment by itMcdull** [comment]
大佬可以看下是什么问题吗

**Comment by itMcdull** [comment]
添加输入框之后 点击输入框就会出现

**Comment by itMcdull** [comment]
flutter 版本Flutter  (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale zh-Hans-HK)

**Comment by MMMzq** [comment]
你有使用`Overlay`包住输入框吗?
