### ISSUE TITLE
[ProxyDispose.disposeCallback] 不能正常回调时导致的问题

### ISSUE THREAD

**Issue by wangzhiming8916** [MMMzq/bot_toast#77]
![image](https://user-images.githubusercontent.com/27940976/91246751-4013e880-e783-11ea-8814-408d4c86ca32.png)

当 ToastWidget 首桢没有渲染完成前就被 remove 时，ProxyDispose.disposeCallback 就不会被回调，如果指定了 BackButtonBehavior.ignore，PopTestFunc 也不能被移除，就会导致 Android 的系统返回键失效。

```Dart
BotToast.showLoading();
Future.then((_) {
  // 如果这里在 ToastWidget 首桢渲染完成之前被执行，就会出现 Android 系统返回键失效的问题。
  BotToast.removeAll(BotToast.loadKey);
});
```

**Comment by zsp754642483** [comment]
我的天，终于找到返回键失效问题所在，哭啦，我测了半天，都找不出所以然

**Comment by MMMzq** [comment]
晚上会发个新版本解决这个问题😰

**Comment by MMMzq** [comment]
升级`v3.0.4`解决此bug

**Comment by wangzhiming8916** [comment]
可以了，验证通过
