### ISSUE TITLE
請問可調整 Toast 的寬度 ?

### ISSUE THREAD

**Issue by dodatw** [MMMzq/bot_toast#78]
請問可調整toast的寬度嗎? 目前看起來有點窄, 如果長一點的字串會沒那麼好看.

```
constraints:
                constraints.copyWith(maxWidth: constraints.biggest.width * 0.6),

```
我看code 似乎被限制在0.6. 可把這個值開出來由外面設定嗎 ?

謝謝

**Comment by MMMzq** [comment]
对于此类需求可参看:#33

**Comment by dodatw** [comment]
我試過 showCustomText 
但他最後還是不會改到 TextToast 中的 constraints 參數. 他是定值不能改.
`constraints.copyWith(maxWidth: constraints.biggest.width * 0.6),`

建議0.6開放給外面設定.


Thanks.

**Comment by MMMzq** [comment]
- 你可以不使用`bot_toast`自带的`TextToast`,而是自定义一个`TextToast`并且配合`showCustomText`方法

- 主要是现在方法的入参已经太多了,如不是必要的参数不会再轻易添加了,请谅解

**Comment by dodatw** [comment]
我照你說的改成功了!
