### ISSUE TITLE
可否提供初始化方式的选择

### ISSUE THREAD

**Issue by DinoDom** [MMMzq/bot_toast#79]
3.0版本后初始化方式是在builder中,如果我的项目本来就有自定义的builder的话无法初始化了,我现在只能把版本降到2.x了,请问还有其他办法可以解决吗?

**Comment by MMMzq** [comment]
请看文档:https://github.com/MMMzq/bot_toast#3-initialization-bottoast

**Comment by DinoDom** [comment]
谢谢
