### ISSUE TITLE
希望可以调整normal animation和 fade animation的时长

### ISSUE THREAD

**Issue by LastMonopoly** [MMMzq/bot_toast#8]

**Comment by MMMzq** [comment]
@LastMonopoly 
这个是我现在在做的事情,昨天已经把动画的处理方式给重构了,今晚应该就可以加上此功能,并且可以自定义动画😃。
但是要等几天等到2.0版本一起释出;

**Comment by LastMonopoly** [comment]
厉害了，等你好消息！

**Comment by MMMzq** [comment]
@LastMonopoly 
hey, boy
2.0已经释出你可以尝试一下啦
