### ISSUE TITLE
The usage of 'cancelFunc' is strange!

### ISSUE THREAD

**Issue by ComexGit** [MMMzq/bot_toast#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**

**Comment by MMMzq** [comment]
你可以说说你的看法 :)
