### ISSUE TITLE
toastBuilder所创建的widget不能使用Navigator

### ISSUE THREAD

**Issue by a27919478** [MMMzq/bot_toast#83]
I/flutter (30346): The following assertion was thrown while handling a gesture:
I/flutter (30346): Navigator operation requested with a context that does not include a Navigator.
I/flutter (30346): The context used to push or pop routes from the Navigator must be that of a widget that is a
I/flutter (30346): descendant of a Navigator widget.
I/flutter (30346): 
I/flutter (30346): When the exception was thrown, this was the stack:

在toastBuilder内部创建了一个StatefulWidget中使用Navigator.of(context).push打开页面
报了个这个错误

**Comment by MMMzq** [comment]
这个MaterialApp是`builder`参数的导致的问题,如果你想使用`Navigator.of(context).push` 请尝试使用闭包途径获取其他`context`

**Comment by a27919478** [comment]
了解了，感谢
