### ISSUE TITLE
flutter build error

### ISSUE THREAD

**Issue by roopa1712** [MMMzq/bot_toast#84]
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
    Receiver: null
    Tried calling: call()
    #0      BotToast.showEnhancedWidget.<anonymous closure> (package:bot_toast/src/toast.dart:774)
    <asynchronous suspension>

**Comment by MMMzq** [comment]
I can't reproduce this error, can you provide an error example? :}
