### ISSUE TITLE
Tried calling: addObserver(Instance of 'BotToastWidgetsBindingObserver')

### ISSUE THREAD

**Issue by zhf99love** [MMMzq/bot_toast#87]
runApp(ProviderScope(
    child: MaterialApp(
      title: 'JR SHOP',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      builder: BotToastInit(),
      navigatorObservers: [BotToastNavigatorObserver()],
      home: MainPage(),
    ),
  ));

BUG：
E/flutter (11188): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'addObserver' was called on null.
E/flutter (11188): Receiver: null
E/flutter (11188): Tried calling: addObserver(Instance of 'BotToastWidgetsBindingObserver')
E/flutter (11188): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (11188): #1      new BotToastWidgetsBindingObserver._ (package:bot_toast/src/bot_toast_init.dart:16:29)
E/flutter (11188): #2      BotToastWidgetsBindingObserver._singleton (package:bot_toast/src/bot_toast_init.dart:22:38)
E/flutter (11188): #3      BotToastWidgetsBindingObserver._singleton (package:bot_toast/src/bot_toast_init.dart)
E/flutter (11188): #4      BotToastInit (package:bot_toast/src/bot_toast_init.dart:51:34)
E/flutter (11188): #5      main (package:jr_shop/main.dart:15:16)
E/flutter (11188): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (11188): #7      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (11188): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11188): #9      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (11188): #10     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (11188): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (11188): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (11188): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Environment：
bot_toast: ^3.0.4
Flutter 1.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (16 hours ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1

**Comment by MMMzq** [comment]
I use `flutter 1.22.1` to run the `example` and it works normally

**Comment by MMMzq** [comment]
You need to call `WidgetsFlutterBinding.ensureInitialized()` before `runApp`, or use `StatelessWidget` to wrap `MaterialApp`

**Comment by mdanialr** [comment]
> You need to call `WidgetsFlutterBinding.ensureInitialized()` before `runApp`, or use `StatelessWidget` to wrap `MaterialApp`

thanks.. thats work.
