### ISSUE TITLE
No Overlay widget found.

### ISSUE THREAD

**Issue by Yonkers** [MMMzq/bot_toast#89]
Widget in BotToast can't us widget with tooltip, such as IconButton, ToolTip

version: 3.x

```
No Overlay widget found.
```

**Comment by MMMzq** [comment]
see #71

**Comment by MMMzq** [comment]
You can wait for `3.0.5` version to be released, `3.0.5` will solve this problem

**Comment by Yonkers** [comment]
OK, thanks you! just thinking is there a better way to do this.
