### ISSUE TITLE
可否考虑增加hideLoading

### ISSUE THREAD

**Issue by LKTPD** [MMMzq/bot_toast#9]
你好！对应**BotToast.showLoading()**，可否考虑增加**hideLoading()**，默认不是showLoading的Duration参数，一直显示等待界面，而当后续流程中用户可以通过代码调用hideLoading()手动结束Loading显示。谢谢！ @MMMzq

**Comment by MMMzq** [comment]
@LKTPD 
你可以使用showLoading()的返回返回值进行关闭😁,所有showXxxToast都会返回一个CancelFunc函数,调用即可关闭对应的Toast

**Comment by MMMzq** [comment]
如果还有问题要反馈，可以选择重新打开

**Comment by slemankfa** [comment]
Dear @MMMzq Thanks for this sweet work 

but I can't understand Kanji or Chinese char I was trying to translate and try to do as you explain but I don't do it very well can you do a simple example to close BotToast.showLoading(); 
how I can usecancel Fun ? 
can you write the code, Thanks in advance

**Comment by MMMzq** [comment]
@slemankfa 

Of course ！
Example:
```dart
CancelFunc cancel = BotToast.showLoading()； //popup loading toast
cancel() ;  //close loading toast
```
Note: all `ShowXxxToast` functions will return `CancelFunc`

**Comment by slemankfa** [comment]
> @slemankfa
> 
> Of course ！
> Example:
> 
> ```dart
> CancelFunc cancel = BotToast.showLoading()； //popup loading toast
> cancel() ;  //close loading toast
> ```
> 
> Note: all `BotToast.showXxx` functions will return `CancelFunc`

Thank you, I was wondering how to use cancelFun in the correct way. 
you dif a great Job ^^>

**Comment by Martibis** [comment]
@MMMzq Is there a way to cancel all currently open BotToasts?

**Comment by MMMzq** [comment]
`BotToast.cleanAll()`

**Comment by MMMzq** [comment]
> @MMMzq Is there a way to cancel all currently open BotToasts?

`BotToast.cleanAll()`

**Comment by Martibis** [comment]
Just what I needed thanks! Amazing work by the way!
