### ISSUE TITLE
No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by sunjianan9900** [MMMzq/bot_toast#90]
使用方法：
`final botToastBuilder = BotToastInit();`
builder: (context, child) {
        child = ResponsiveWrapper.builder(
            BouncingScrollWrapper.builder(context, child),
            // maxWidth: 1200,
            minWidth: 450,
            defaultScale: true,
            breakpoints: [
              ResponsiveBreakpoint.resize(450, name: MOBILE),
              ResponsiveBreakpoint.autoScale(800, name: TABLET),
              ResponsiveBreakpoint.autoScale(1000, name: TABLET),
              ResponsiveBreakpoint.resize(1000, name: DESKTOP),
              ResponsiveBreakpoint.autoScale(2460, name: "4K"),
            ],
            background: Container(color: background)); //do something
        child = botToastBuilder(context, child);
        return child;
      },

`/SDK/BETA/flutter/.pub-cache/hosted/pub.flutter-io.cn/bot_toast-3.0.4/lib/src/keyboard_safe_area.dart:16:50: Error: No named parameter with the name 'nullOk'.
    MediaQueryData data = MediaQuery.of(context, nullOk: true);
                                                 ^^^^^^
/Volumes/Jianan/SDK/BETA/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^
Failed to compile application.`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-6.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)
    ! Error: Jianan-iPad Air2 is busy: Copying cache files from device. Xcode
      will continue when Jianan-iPad Air2 is finished. (code -10)

! Doctor found issues in 1 category.

**Comment by MMMzq** [comment]
这个与`bot_toast`无关,是`MediaQuery.of(context, nullOk: true)`参数错误引起的

**Comment by sunjianan9900** [comment]
<img width="1161" alt="WX20201031-100343@2x" src="https://user-images.githubusercontent.com/10936316/97768765-734a6d80-1b60-11eb-8396-f47a025b50fb.png">
我去bot_toast源码里面把nullOk: true给删掉了，应该是不兼容新版的flutter？MediaQuery不是第三方的包吧

**Comment by MMMzq** [comment]
我看你版本是`1.24`,应该是不兼容的

**Comment by sunjianan9900** [comment]
> 我看你版本是`1.24`,应该是不兼容的

好的，把那个参数删了就好了
