### ISSUE TITLE
build error with flutter version 1.24.0-7.0.pre.50

### ISSUE THREAD

**Issue by paozhuanyinyu** [MMMzq/bot_toast#91]
../../../../../.pub-cache/hosted/pub.flutter-io.cn/bot_toast-3.0.4/lib/src/keyboard_safe_area.dart:16:50: Error: No named parameter with the name 'nullOk'.
    MediaQueryData data = MediaQuery.of(context, nullOk: true);
                                                 ^^^^^^
../../../../flutter/flutter_source/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {

flutter version:
[✓] Flutter (Channel master, 1.24.0-7.0.pre.50, on Mac OS X 10.15.7 19H2
    darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)

**Comment by MMMzq** [comment]
You can try to use stable channel

**Comment by paozhuanyinyu** [comment]
ok

**Comment by MMMzq** [comment]
`v3.0.5` released
