### ISSUE TITLE
showText方法怎么设置不允许点击

### ISSUE THREAD

**Issue by zhafuchun** [MMMzq/bot_toast#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**

**Comment by MMMzq** [comment]
因为最开始`showText`的使用场景只是作为辅助提醒使用,因此`allowClick`属性被强制设置为true,并没有开放出来.但是如果有需要的话我可以开放此属性

**Comment by fyang0728** [comment]
> 因为最开始`showText`的使用场景只是作为辅助提醒使用,因此`allowClick`属性被强制设置为true,并没有开放出来.但是如果有需要的话我可以开放此属性

能不能把这个功能开放，让使用者自己选择？现在需要这种效果。
