### ISSUE TITLE
在使用showCustomLoading时 无法setstate影响内部weiget

### ISSUE THREAD

**Issue by shaonianahua** [MMMzq/bot_toast#95]
我在做一个进度条的功能,然后使用了showCustomLoading,然后toastBuilder里的widget调用了外部的变量,然而外部变量setstate时在toastBuilder内部并没有被影响,这样导致了我的进度条无法检测到进度,请问这个可以解决吗,谢谢

**Comment by MMMzq** [comment]
出现这种问题是因为`toast`里面的widget并不是外部widget的子widget,所以你调外部的setState是没有用的,你可以用一些类似于通知的东西,在调用外部setState的时候也触发一下通知让`toast`里的widget自己去setState

**Comment by shaonianahua** [comment]
我大概理解你的意思了 但这个通知要怎么做 需要用到provider吗

**Comment by MMMzq** [comment]
你可以使用`ChangeNotifier`,`Stream`,`StatefulBuilder`都行,方式很多,你自己找找吧
