### ISSUE TITLE
OverlayEntry会一直在toast层的下层

### ISSUE THREAD

**Issue by gohopo** [MMMzq/bot_toast#99]
**Describe the bug**
更新3.0.5版本之后,OverlayEntry会一直在toast层的下面,导致一些动画效果看不见,之前的版本是没问题的,最近才升级的3版本
貌似是[Use Stack instead of Overlay](https://github.com/MMMzq/bot_toast/commit/58eb6cb1f3285a6352cf24e39e21383d060cf9a1)这个导致的

![QQ截图20201204153427](https://user-images.githubusercontent.com/8192266/101135061-3df4dc00-3646-11eb-84d0-bdf7d5b9a260.png)
这个界面是对话框中点击按钮,用overlay展示了一个全屏的图片动画

**To Reproduce**

**Expected behavior**
后创建的OverlayEntry能覆盖toast弹出的界面

**Screenshots**

**Version (please complete the following information):**
 - Flutter Version: 1.24.0-8.0.pre.375
 - OS: Android
 - BotToast Version : 3.0.5

**Comment by MMMzq** [comment]
跟这个没有关系,在`3.0.5`之前,后面调用的`showXxxx`显示顺序是不确定的,而`3.0.5`版本优化了这部分,现在的显示顺序是后调用的`showXxxx`放在`Stack`最顶层

你可以看看这个:  https://github.com/MMMzq/bot_toast/issues/88#issuecomment-719224586

**Comment by gohopo** [comment]
那新版本的toast和OverlayEntry有冲突吗?showXxxx之后insert一个OverlayEntry,就像上面图里的那样,一直在toast下面
这是我的初始化方式
```
Widget build(BuildContext context) {
    return MultiProvider(
      providers: providers,
      child: Consumer<AppState>(
        builder: (context,appState,child) => RepaintBoundary(
          key: appState.repaintBoundary,
          child: RefreshConfiguration(
            shouldFooterFollowWhenNotFull: (status) => false,
            child: GestureDetector(
              onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
              child: MaterialApp(
                title: AppConfig.name,
                theme: appState.themeData(),
                darkTheme: appState.themeData(),
                localizationsDelegates: [
                  RefreshLocalizations.delegate
                ],
                navigatorObservers: [LocatorManager.routerManager,BotToastNavigatorObserver()],
                onGenerateRoute: LocatorManager.routerManager.generateRoute,
                initialRoute: RouteName.splash,
                builder: BotToastInit(),
              ),
            )
          )
        )
      )
    );
  }
```

其实我试过用另一个toast来显示,但是点击事件不穿透,就是想要image不阻挡事件,但toast内容下面有个listener阻挡
```
Listener(
 onPointerDown: clickClose ? (_) => dismissFunc() : null,
 behavior: allowClick ? HitTestBehavior.translucent  : HitTestBehavior.opaque,
 child: const SizedBox.expand(),
),
```

**Comment by MMMzq** [comment]
你的`OverlayEntry`也是使用`BotToast.showXxxx`来插入的吗？

或者你可以把`OverlayEntry`插入的逻辑放上来,这样我能更快理解你的需求

**Comment by gohopo** [comment]
是用的navigator插入的
下面的`effect.getWidget(fit:BoxFit.fitWidth)`返回的是`Image`组件
```
 Future show(Effect effect) async {
    if(effect.network) await SfCacheManager().getSingleFile(effect.imagePath);
    var entry = OverlayEntry(
      builder: (context) => IgnorePointer(
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: Colors.black87,
          ),
          child: effect.getWidget(fit:BoxFit.fitWidth)
        ),
      ),
    );
    LocatorManager.routerManager.navigator.overlay.insert(entry);
    await Future.delayed(Duration(milliseconds:effect.duration));
    entry.remove();
    PaintingBinding.instance.imageCache.clear();
    await Future.delayed(Duration(milliseconds:1000));
  }
```

**Comment by MMMzq** [comment]
如果是`navigator`插入的确实是你说的那种情况
以前是2.x版本是使用`navigator`内部的`Overlay`实现的,后来有很多问题,3.x就使用了`MaterialApp.builder`+`stack`来实现了

现在3.x的情况:
```
Stack(
  [
    Toast1,    //BotToast插入的Toast会放在这里
    Toast2,
    ...,  
    Navigator(
       Overlay(
        [OverlayEntry1,OverlayEntry2,...]  //navigator插入的OverlayEntry会放在这里
       )
    )
  ]
)
```

**Comment by MMMzq** [comment]
> 其实我试过用另一个toast来显示,但是点击事件不穿透,就是想要image不阻挡事件,但toast内容下面有个listener阻挡
你可以尝试使用`IgnorePointer`包装一下,因为很多动画,图片本身都是会吸收事件

**Comment by gohopo** [comment]
> > 其实我试过用另一个toast来显示,但是点击事件不穿透,就是想要image不阻挡事件,但toast内容下面有个listener阻挡
> 
> 你可以尝试使用`IgnorePointer`包装一下`Image`,因为很多动画,图片本身都是会吸收事件

这个我也试过了,还是不穿透

**Comment by MMMzq** [comment]
> > > 其实我试过用另一个toast来显示,但是点击事件不穿透,就是想要image不阻挡事件,但toast内容下面有个listener阻挡
> > 
> > 
> > 你可以尝试使用`IgnorePointer`包装一下`Image`,因为很多动画,图片本身都是会吸收事件
> 
> 这个我也试过了,还是不穿透

`allowClick`设置为true,`ignoreContentClick`设置为true,这种试过吗?

**Comment by gohopo** [comment]
这些也试过了,我还试着在`showEnhancedWidget`最前面直接返回`toastBuilder(dismissFunc)`,还是无法穿透,所以跟这些参数应该无关吧
而用`Overlay`是可以穿透的

**Comment by MMMzq** [comment]
正常来讲不应该啊,你用BotToast显示的`Image`的代码是怎样的?

**Comment by gohopo** [comment]
```
EasyDialog.show(
    allowClick: true,
    ignoreContentClick: true,
    builder: (dialog) => IgnorePointer(
      child: effect.getWidget(fit:BoxFit.fitWidth)
    )
);
```
抱歉,我找到原因了,
这个`EasyDialog.show`是封装的[SfDialog.onShow](https://github.com/gohopo/social_foundation/blob/master/lib/widgets/toast.dart#L23),
因为之前弹toast会有双下划线,提示要有`Material`祖先组件,所以`wrapAnimation`参数就默认加了
`wrapAnimation ?? (controller,cancelFunc,widget) => Material(color:Colors.transparent,child:widget)`
就是这个导致不穿透的
不好意思,麻烦你了
